import { StyleSheet } from "react-native";
import { globalColors } from "../../../GlobalStyles";

export default StyleSheet.create({
  mapContainer: {
    height: "70%",
    justifyContent: "center",
    width: "100%",
    borderTopEndRadius: 30,
    borderTopStartRadius: 30,
    overflow: "hidden",
    marginBottom: 10,
  },
  buttonContainer: {
    justifyContent: "space-between",
    alignItems: "center",
    height: "5%",
    backgroundColor: "#fff",
    flexDirection: "row",
    width: "90%",
    paddingLeft: 20,
    borderRadius: 50,
    alignSelf: "center",
    margin: 10,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    // bottom: "20%",
  },
  // mapButtons: {
  //   width: 40,
  //   height: 40,
  //   justifyContent: "center",
  //   backgroundColor: globalColors.orange,
  //   alignItems: "center",
  // },
  buttonText: {
    fontFamily: "montserrat-regular",
    fontSize: 25,
    color: "#fff",
  },
  autoCompleteResaults: {
    backgroundColor: "#fff",
    padding: 10,
    borderBottomWidth: 0.3,
    width: "100%",
    alignSelf: "center",
    flexDirection: "column",
  },
  autoCompleteResaultText: {
    fontFamily: "montserrat-bold",
    fontSize: 14,
  },
  autoCompleteResaultTextSecondery: {
    fontFamily: "montserrat-regular",
    fontSize: 12,
  },
  circleMarker: (state = {}) => ({
    width: state.width,
    height: state.width,
    borderRadius: state.width,
    // borderWidth: 1,
    position: "absolute",
    left: state.x - state.width / 2,
    top: state.y - state.width / 2,
    alignItems: "center",
    // backgroundColor: "rgba(117, 26, 255,0.3)",
    // borderStyle: "dashed",
    // borderColor: "#9304FF",
    justifyContent: "center",
  }),
  pinButton: {
    position: "absolute",
    width: "50%",
    height: 60,
    bottom: "15%",
    alignSelf: "center",
  },
  pinTextStyle: {
    fontFamily: "montserrat-light",
    fontSize: 12,
    color: "#9304FF",
    textTransform: "capitalize",
    width: 70,
    textAlign: "center",
    position: "absolute",
    bottom: 10,
  },
  mapButtons: {
    width: 40,
    height: 40,
    justifyContent: "center",
    backgroundColor: globalColors.purple,
  },
  leftButton: {
    borderBottomLeftRadius: 50,
    borderTopLeftRadius: 50,
    borderTopEndRadius: 0,
    borderBottomRightRadius: 0,
  },
  rightButton: {
    borderBottomRightRadius: 50,
    borderTopRightRadius: 50,
    borderTopStartRadius: 0,
    borderBottomLeftRadius: 0,
    borderStartColor: "#000",
    borderStartWidth: 0.2,
  },
  mapTitle: {
    fontFamily: "montserrat-bold",
    fontSize: 14,
    textTransform: "uppercase",
  },
  rangeStyle: {
    fontFamily: "montserrat-bold",
    fontSize: 12,
    color: "#9304FF",
  },
});
