import { StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../GlobalStyles";

export default StyleSheet.create({
  mapContainer: {
    height: "70%",
    justifyContent: "center",
    width: "100%",
    borderTopEndRadius: RFValue(15, 414),
    borderTopStartRadius: RFValue(15, 414),
    overflow: "hidden",
    marginBottom: RFValue(5, 414),
  },
  buttonContainer: {
    justifyContent: "space-between",
    alignItems: "center",
    height: "5%",
    backgroundColor: "#fff",
    flexDirection: "row",
    width: "90%",
    paddingLeft: RFValue(10, 414),
    borderRadius: RFValue(25, 414),
    alignSelf: "center",
    margin: RFValue(5, 414),
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    // bottom: "20%",
  },
  // mapButtons: {
  //   width: 40,
  //   height: 40,
  //   justifyContent: "center",
  //   backgroundColor: globalColors.orange,
  //   alignItems: "center",
  // },
  buttonText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(12.5, 414),
    color: "#fff",
    textAlign: "center",
  },
  autoCompleteResaults: {
    backgroundColor: "#fff",
    padding: RFValue(5, 414),
    borderBottomWidth: 0.3,
    width: "100%",
    alignSelf: "center",
    flexDirection: "column",
  },
  autoCompleteResaultText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
  },
  autoCompleteResaultTextSecondery: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6, 414),
  },
  circleMarker: (state = {}) => ({
    width: state.width,
    height: state.width,
    borderRadius: state.width,
    // borderWidth: 1,
    position: "absolute",
    left: state.x - state.width / 2,
    top: state.y - state.width / 2,
    alignItems: "center",
    // backgroundColor: "rgba(117, 26, 255,0.3)",
    // borderStyle: "dashed",
    // borderColor: "#9304FF",
    justifyContent: "center",
  }),
  pinTwoButtons: {
    width: "40%",
    height: RFValue(30, 414),
    alignSelf: "center",
  },
  pinButton: {
    position: "absolute",
    width: "50%",
    height: RFValue(30, 414),
    bottom: "15%",
    alignSelf: "center",
  },
  pinTextStyle: {
    fontFamily: "montserrat-light",
    fontSize: RFValue(6, 414),
    color: "#9304FF",
    textTransform: "capitalize",
    width: RFValue(35, 414),
    textAlign: "center",
    position: "absolute",
    bottom: RFValue(5, 414),
  },
  mapButtons: {
    width: RFValue(20, 414),
    height: RFValue(20, 414),
    justifyContent: "center",
    backgroundColor: globalColors.purple,
  },
  leftButton: {
    borderBottomLeftRadius: RFValue(25, 414),
    borderTopLeftRadius: RFValue(25, 414),
    borderTopEndRadius: 0,
    borderBottomRightRadius: 0,
  },
  rightButton: {
    borderBottomRightRadius: RFValue(25, 414),
    borderTopRightRadius: RFValue(25, 414),
    borderTopStartRadius: 0,
    borderBottomLeftRadius: 0,
    borderStartColor: "#000",
    borderStartWidth: 0.2,
  },
  mapTitle: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    textTransform: "uppercase",
  },
  rangeStyle: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    color: "#9304FF",
  },
  saveButton: {
    borderWidth: 0.3,
    padding: RFValue(5, 414),
    borderRadius: RFValue(20, 414),
    borderColor: globalColors.purple,
    shadowColor: "#000",
    backgroundColor: "#fff",
    shadowOffset: {
      width: 1,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 1,
  },
  mapButtonsContainer: {
    flexDirection: "row",
    alignSelf: "center",
    bottom: "15%",
    width: "100%",
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
});
