import { StyleSheet, PixelRatio } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { globalColors } from "../../../../GlobalStyles";
export const colors = {
  black: "#1a1917",
  gray: "#888888",
  background1: "#751AFF",
  background2: "#6268FF",
};
const styles = StyleSheet.create({
  safeAreaView: {
    backgroundColor: "#0000",
    height: "100%",
  },
  popupOverlay: {
    height: "100%",
  },
  uplaodPercentageText: {
    position: "absolute",
    fontFamily: "montserrat-bold",
    fontSize: 8,
    color: "#FFF",
    textAlign: "center",
  },
  uplaodPercentage: {
    fontSize: 16,
    color: "#fff",
    fontFamily: "montserrat-bold",
    textAlign: "center",
    alignSelf: "center",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  uplaodText: {
    justifyContent: "center",
    fontSize: 12,
    color: "white",
    fontFamily: "montserrat-medium",
    alignSelf: "center",
    paddingTop: 10,
    textAlign: "center",
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  loadingSafeArea: {
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  footerButtonsContainer: {
    // display: "flex",
    flexDirection: "row",
  },
  errorMsg: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-medium",
    fontSize: hp(1.7),
  },
  video: {
    width: "100%",
    height: "100%",
    opacity: 0.5,
  },
  transition: {
    height: "100%",
  },
  contentContainer: {
    alignSelf: "center",
    height: "95%",
    width: "90%",
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  mainSafeArea: {
    height: "100%",
    backgroundColor: "#0000",
  },
  blankView: {
    backgroundColor: "rgba(0,0,0,0.5)",
    opacity: 0.5,
    height: "100%",
    width: "100%",
  },
  title: {
    fontSize: 16,
    color: "#fff",
    fontFamily: "montserrat-bold",
    textAlign: "center",
    alignSelf: "center",
    position: "absolute",
    top: "70%",
    textDecorationLine: "underline",
  },
  mediaButtonMsg: {
    textAlign: "center",
    paddingTop: 23,
    fontFamily: "montserrat-medium",
    fontSize: 14,
    width: 150,
    color: "#FF9D00",
  },
  icon: {
    color: "#fff",
    // paddingLeft: 5,
    alignSelf: "center",
    justifyContent: "center",
    textAlign: "center",
    fontSize: 50,
    paddingTop: 12,
  },
  inputMiddleButton: {
    position: "absolute",
    backgroundColor: "#FF9D00",
    alignSelf: "center",
    width: 90,
    height: 90,
    borderRadius: 45,
    borderColor: "transparent",
    top: "50%",
    left: "50%",
    flexDirection: "column",
    opacity: 1,
    transform: [
      {
        translateX: -50,
      },
      {
        translateY: -50,
      },
    ],
  },
  inputBrand: {
    position: "absolute",
    alignSelf: "center",
    width: 250,
    height: 50,
    top: "2%",
    left: "8%",
    borderColor: "transparent",
    transform: [
      {
        translateX: -5,
      },
      {
        translateY: -2,
      },
    ],
  },
  inputHeadline: {
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    borderColor: "transparent",
    paddingLeft: 15,
    height: 50,
    backgroundColor: "#0003",
    borderRadius: 40,
  },
  container: {
    backgroundColor: "#0000",
  },
  inputText: {
    fontFamily: "montserrat-regular",
    fontSize: 13 / PixelRatio.getFontScale(),
    color: "#fff",
    marginLeft: 8,
    // height: "100%",
  },

  placeholder: {
    borderRadius: 30,
    overflow: "hidden",
    alignSelf: "center",
    width: "100%",
    flex: 1,
    backgroundColor: "#0003",
    justifyContent: "space-evenly",
    padding: 20,
    // paddingBottom: 30,
  },
  placeholder1: {
    // opacity: 0.5,
    borderRadius: 30,
    overflow: "hidden",
    alignSelf: "center",
    width: "100%",
    height: "65%",
    zIndex: 0,
    backgroundColor: "#0003",
    justifyContent: "center",
    marginVertical: 20,
  },
  button: {
    alignSelf: "center",
    width: wp(10),
    height: hp(7.5),
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
    marginHorizontal: wp(10),
  },

  footerTextStyle: {
    fontSize: 12,
    color: "white",
    fontFamily: "montserrat-medium",
    alignSelf: "center",
  },
  footerStyle: {
    marginVertical: 15,
    alignSelf: "flex-end",
  },
  subtitleHeading: {
    color: "#fff",
    fontSize: 9,
    fontFamily: "montserrat-regular",
    marginLeft: 8,
    textAlign: "left",
  },
  MediaOptionsStyle: {
    width: "80%",
    flexDirection: "row",
    padding: 20,
    justifyContent: "space-evenly",
    alignItems: "center",
    marginVertical: 10,
  },

  MediaOptionsTitle: {
    fontFamily: "montserrat-bold",
    color: globalColors.orange,
    fontSize: 16,
  },
  MediaOptionsDescription: {
    fontFamily: "montserrat-light",
    color: "#fff",
    fontSize: 13,
  },
  subText: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-light",
    fontSize: hp(1.7),
  },
  addLogoStyle: {
    borderRadius: 40,
    height: "25%",
    width: "100%",
    alignSelf: "center",
    backgroundColor: "#0003",
    alignItems: "center",
    justifyContent: "center",
  },
  addLogoTextStyle: {
    color: globalColors.white,
    fontFamily: "montserrat-regular",
    fontSize: 13,
    textAlign: "center",
    width: 250,
  },
  changeLogoStyle: {
    borderRadius: 30,
    width: "100%",
    height: "20%",
    alignSelf: "center",
    overflow: "hidden",
    // paddingVertical: 10,
  },
  proceedButtonRTL: {
    width: 50,
    height: 50,
  },
  logoStyle: {
    height: "100%",
    width: "100%",
    alignSelf: "center",
    opacity: 0.7,
  },
  logoEdit: {
    position: "absolute",
    alignSelf: "flex-end",
    right: 10,
    top: 10,
  },
  infoText: {
    fontFamily: "montserrat-regular",
    fontSize: 12,
    color: globalColors.purple,
  },
});

export default styles;
