import { StyleSheet, PixelRatio, Platform, I18nManager } from "react-native";
import {
  widthPercentageToDP,
  heightPercentageToDP,
} from "react-native-responsive-screen";
import { globalColors } from "../../../../GlobalStyles";

const styles = StyleSheet.create({
  outerView: {
    flex: 1,
    backgroundColor: "#f8f8f8",
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "column",
  },
  safeAreaViewContainer: {
    // flex: 1,
  },
  feildView: { display: "flex", flexDirection: "row", marginVertical: 8 },
  plusIconView: {
    borderColor: globalColors.purple,
    borderWidth: 1,
    width: 17,
    height: 17,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#9300FF50",
  },
  subHeading: {
    fontFamily: "montserrat-bold",
    fontSize: 12,
    color: "#75647C",
    textTransform: "uppercase",
  },
  subText: {
    fontFamily: "montserrat-regular",
    fontSize: 12,
    color: "#75647C",
    marginTop: 4,
    // height: null,
  },
  previewBtn: {
    borderColor: "#75647C",
    borderWidth: 1,
    height: 50,
    width: "35%",
  },
  saveBtn: {
    height: 50,
    width: "50%",
  },
  previewText: {
    color: "#75647C",
    fontSize: 14,
    fontFamily: "montserrat-bold",
  },
  imageViewContainer: {
    // flex: 1,
    marginHorizontal: 10,
    flexDirection: "row",
    // height: 250,
  },
  image: {
    width: 140,
    height: 230,
    borderRadius: 20,
    marginHorizontal: 5,
  },
  fieldTextView: { marginHorizontal: 8 },
  priceCard: {
    backgroundColor: "#F8F8F8",
    width: "80%",
    alignSelf: "center",
    padding: 10,
    borderRadius: 20,
  },
  priceHeaderCard: {
    display: "flex",
    flexDirection: "row",
  },
  priceText: {
    fontSize: 12,
    textTransform: "uppercase",
    color: "#75647C",
    marginHorizontal: 15,
    fontFamily: "montserrat-bold",
  },
  priceSubText: {
    fontSize: 12,
    fontFamily: "montserrat-regular",
    color: "#75647C",
    marginHorizontal: 15,
  },
  countryOuterView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    justifyContent: "space-around",
    // marginHorizontal: 15,
  },
  countryEachView: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    // marginHorizontal: 8,
  },
  flagImage: { borderRadius: 25, height: 30, width: 30 },
  countryText: {
    fontFamily: "montserrat-regular",
    fontSize: 12,
    color: "#9300FF",
    marginVertical: 4,
  },
  bottomView: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    paddingBottom: 15,
  },
  inputView: {
    width: "70%",
    borderRadius: 25,
    // borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    backgroundColor: "#FFF",
    height: 35,
    color: "#75647C",
    fontSize: 12,
    fontFamily: "montserrat-regular",
    paddingHorizontal: 15,
  },
  saveButton: {
    width: "30%",
    height: 35,
  },
  addMediaText: {
    fontSize: 9,
    fontFamily: "montserrat-regular",
    color: globalColors.purple,
    textTransform: "uppercase",
    textAlign: "center",
    marginTop: 8,
  },
  placeholderView: {
    width: 140,
    height: 230,
    borderRadius: 20,
    marginHorizontal: 5,
    borderWidth: 2,
    borderColor: globalColors.purple,
    backgroundColor: "#9304FF16",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  imagePlaceholder: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "100%",
    borderRadius: 20,
    opacity: 0.75,
  },
  flagActiveImage: {
    borderWidth: 2,
    borderColor: globalColors.purple,
  },
  bottomBtns: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginVertical: 20,
    bottom: 10,
    position: "absolute",
    // alignSelf: "flex-end",
  },
});
export default styles;
