import { StyleSheet, Platform, PixelRatio, I18nManager } from "react-native";
import {
  heightPercentageToDP,
  widthPercentageToDP,
} from "react-native-responsive-screen";
import { globalColors } from "../../../../GlobalStyles";
export const colors = {
  black: "#1a1917",
  gray: "#888888",
  background1: "#751AFF",
  background2: "#751AFF",
};
const styles = StyleSheet.create({
  safeArea: {
    height: "100%",
    flex: 1,
    backgroundColor: "#0000",
  },
  mainContainer: {
    // backgroundColor: 'rgba(255, 255, 255, 0.3)',
    backgroundColor: "#0000",
  },
  container: {
    // borderTopRightRadius: 30,
    // borderTopLeftRadius: 30,
    backgroundColor: "#0000",
    // marginTop: hp(2),
    overflow: "hidden",
    width: "100%",
    height: "100%",
    flex: 1,
  },
  backgroundViewWrapper: {
    ...StyleSheet.absoluteFillObject,
  },
  imageBackgroundViewWrapper: {
    position: "absolute",
    // left: -60,
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  videoBackgroundViewWrapper: {
    width: "100%",
    height: "100%",
  },
  contentContainer: {
    height: "93%",
    // paddingTop: ,
  },
  subHeadings: {
    color: globalColors.gray,
    fontFamily: "montserrat-bold",
    fontSize: 16,
    paddingVertical: 5,
    paddingHorizontal: 30,
    textAlign: "left",
  },
  moneyInputContainer: {
    flexDirection: "column",
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 15,
    alignSelf: "center",
    justifyContent: "space-around",
    paddingVertical: 10,
  },
  budget: {
    alignSelf: "center",
    color: "#FF9D00",
    fontSize: 25 / PixelRatio.getFontScale(),
    fontFamily: "montserrat-medium",
    textAlign: "center",
    width: "100%",
    paddingBottom: 0,
    width: "100%",
  },
  moreOptionsText: {
    alignSelf: "center",
    color: "#FF9D00",
    fontSize: 14,
    fontFamily: "montserrat-medium",
    textAlign: "center",
    width: "100%",
    bottom: 20,
  },
  budgetInstructionText: {
    color: "#fff",
    fontSize: 11,
    alignSelf: "center",
    paddingHorizontal: 20,
  },
  sliderContainer: {
    marginHorizontal: 40,
    width: "100%",
    alignSelf: "center",
    paddingVertical: 10,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 40,
  },
  budgetSliderText: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    textAlign: "center",
    paddingBottom: 10,
  },
  slider: {
    width: "100%",
    height: 20,
  },
  sliderPlaceHolder: {
    height: 75,
    justifyContent: "center",
  },
  targetList: {
    flexDirection: "column",
    // paddingBottom: 40,
    // height: "50%",
    marginHorizontal: 30,
  },
  targetTouchable: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 8,
    backgroundColor: "#fff",
    borderRadius: 50,
    padding: 10,
  },
  icon: {
    alignSelf: "center",
  },

  chart: {
    // bottom: 0,
    // width: widthPercentageToDP(25)
  },
  bottom: {
    flexDirection: "row",
    justifyContent: "center",
    paddingLeft: 10,
    // height: "14%",
    alignItems: "center",
    alignSelf: "center",
    // width: "100%",
    bottom: 0,
    position: "absolute",
    // flex: 0.55,
    backgroundColor: globalColors.white,
    borderTopWidth: 1,
    borderTopColor: "#75647C21",
    paddingVertical: 20,
  },
  chartText: {
    textTransform: "uppercase",
    color: globalColors.rum,
    textAlign: "center",
    fontFamily: "montserrat-bold",
    fontSize: 13 / PixelRatio.getFontScale(),
  },
  chartTextNum: {
    color: globalColors.rum,
    fontFamily: "montserrat-regular-english",
    fontSize: 16,
    textAlign: "center",
    width: "100%",
    textTransform: "uppercase",
  },
  chartItems: {
    flexDirection: "row",
    // flex: 1,
  },
  reachBarLowerButton: {
    width: 100,
    height: 50,
  },
  reachPeopleView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    // width: "100%",
    flex: 1,
  },
  menutext: {
    paddingLeft: Platform.OS === "android" && I18nManager.isRTL ? 0 : 15,
    paddingRight: Platform.OS === "android" && I18nManager.isRTL ? 15 : 0,
    fontSize: 13,
    fontFamily: "montserrat-bold",
    color: globalColors.gray,
    textAlign: "left",
    textTransform: "uppercase",
  },
  menudetails: {
    paddingLeft: Platform.OS === "android" && I18nManager.isRTL ? 0 : 15,
    paddingRight: Platform.OS === "android" && I18nManager.isRTL ? 15 : 0,
    color: globalColors.gray,

    fontFamily: "montserrat-regular",
    fontSize: 11,
    textAlign: "left",
  },
  flex: {
    flex: 1,
  },
  menuComponentStyle: { top: 0 },
  reachView: {
    // flex: ,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    // width: "100%",
    marginHorizontal: 30,
  },
  existingButton: {
    borderWidth: 2,
    borderColor: "#9300FF",
    paddingHorizontal: 8,
    overflow: "visible",
    marginHorizontal: 0,
  },
  existingButtonText: { fontSize: 12, color: "#9300FF" },
  reachSubHeading: {
    color: globalColors.purple3,
    textTransform: "uppercase",
    fontFamily: "montserrat-bold",
    fontSize: 10 / PixelRatio.getFontScale(),
  },
  reachTextNum: {
    color: globalColors.purple3,
    fontFamily: "montserrat-regular-english",
    fontSize: 10 / PixelRatio.getFontScale(),
    textAlign: "left",
    width: "100%",
    textTransform: "uppercase",
  },
  expectedResultText: {
    color: globalColors.rum,
    fontSize: 12,
    fontFamily: "montserrat-bold",
    textTransform: "uppercase",
    marginVertical: 5,
    marginHorizontal: 20,
    textAlign: "left",
  },
  reachInnerView: {
    flexDirection: "column",
    alignItems: "flex-start",
    marginLeft: 5,
  },
  bottomReachView: { flexDirection: "column", flex: 1 },
  districtOuterView: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 10,
  },
  chooseDistrictText: {
    fontSize: 14,
    color: globalColors.rum,
    fontFamily: "montserrat-bold",
    marginHorizontal: 5,
    textTransform: "uppercase",
  },
  districtInnerView: { marginVertical: 5 },
  districtHeaderView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  districtHeaderInnerView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  radioButton: {
    display: "flex",
    width: 25,
    height: 25,
    backgroundColor: globalColors.white,
    borderRadius: 25,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: globalColors.rum,
  },
  radioButtonSelected: {
    display: "flex",
    alignSelf: "center",
    width: 18,
    height: 18,
    backgroundColor: globalColors.purple,
    borderRadius: 18,
  },
  arrow: {
    color: globalColors.purple,
    alignSelf: "flex-end",
  },
  areaName: {
    fontFamily: "montserrat-regular",
    marginHorizontal: 30,
    color: globalColors.rum,
    marginVertical: 2,
    fontSize: 12,
  },
});

export default styles;
