import { StyleSheet, PixelRatio, I18nManager } from "react-native";
import { globalColors } from "../../../GlobalStyles";

export default StyleSheet.create({
  durationContainer: {
    backgroundColor: "rgba(0,0,0,0.16)",
    borderRadius: 150,
    borderColor: "rgba(0,0,0,0)",
    alignSelf: "center",
    width: "100%",
    borderWidth: 0,
    height: 54,
    alignItems: "center",
    marginBottom: 25,
    marginTop: 10,
    flexDirection: "row",
    paddingHorizontal: 20,
  },
  durationLabel: {
    fontFamily: "montserrat-bold",
    fontSize: 12 / PixelRatio.getFontScale(),
    color: "#fff",
    alignSelf: "flex-start",
    textAlign: I18nManager.isRTL ? "right" : "left",
    textTransform: "uppercase",
    marginTop: 10,
  },
  durationContent: {
    marginLeft: 13,
    width: "90%",
    height: "100%",
    justifyContent: "center",
  },
  durationButtons: {
    alignSelf: "flex-end",
    position: "absolute",
    flexDirection: "row",
    width: "40%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  durButton: {
    width: "50%",
    height: "80%",
    alignSelf: "center",
    justifyContent: "center",
    backgroundColor: globalColors.orange,
  },
  leftButton: {
    borderBottomLeftRadius: 50,
    borderTopLeftRadius: 50,
    borderTopEndRadius: 0,
    borderBottomRightRadius: 0,
  },
  rightButton: {
    borderBottomRightRadius: 50,
    borderTopRightRadius: 50,
    borderTopStartRadius: 0,
    borderBottomLeftRadius: 0,
    borderStartColor: "#000",
    borderStartWidth: 0.2,
  },
  buttonText: {
    fontFamily: "montserrat-regular",
    fontSize: 25,
    color: "#fff",
    textAlign: "center",
  },
  durationData: {
    fontFamily: "montserrat-bold-english",
    color: globalColors.orange,
    fontSize: 14,
    paddingVertical: 5,
    textTransform: "uppercase",
    alignSelf: "flex-start",
  },
});
