import { I18nManager, StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../../GlobalStyles";

export default StyleSheet.create({
  adRejectedTitle: {
    fontSize: RFValue(9, 414),
    fontFamily: "montserrat-bold",
    color: "#EA514B",
    textTransform: "uppercase",
    marginLeft: RFValue(2, 414),
    // paddingVertical: RFValue(2.5, 414),
  },
  rejectedReasonContainer: {
    backgroundColor: "#0005",
    borderRadius: RFValue(17.5, 414),
    flexDirection: "column",
    width: "95%",
    justifyContent: "space-evenly",
    // marginTop: RFValue(5, 414),
  },
  reasonTitle: {
    // textAlign: "left",
    color: globalColors.orange,
    textTransform: "uppercase",
    fontFamily: "montserrat-bold-english",
    fontSize: RFValue(6.5, 414),
    marginBottom: RFValue(2.5, 414),
  },
  rejectedReasonText: {
    textAlign: "left",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-regular-english",
    color: "#fff",
    lineHeight: RFValue(8, 414),
    // textTransform: "uppercase",
    marginLeft: RFValue(2.5, 414),
  },
  rejectedModalTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "space-evenly",
    width: "75%",
  },
  rejectedModalReasonText: {
    // textAlign: "left",
    fontFamily: "montserrat-regular-english",
    fontSize: RFValue(7.5, 414),
    color: "#fff",
    width: "90%",
    marginHorizontal: RFValue(1, 414),
    alignSelf: "center",
  },
  rejectedInfoButton: {
    alignSelf: "flex-end",
    marginHorizontal: RFValue(10, 414),
    marginBottom: RFValue(7.5, 414),
  },
  rejectedReasonView: {
    paddingHorizontal: RFValue(10, 414),
    paddingVertical: RFValue(2.5, 414),
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
  },
  hereReasonsText: {
    fontSize: RFValue(7, 414),
    fontFamily: "montserrat-regular",
    color: "#EA514B",
    paddingTop: RFValue(2.5, 414),
    paddingHorizontal: RFValue(10, 414),
    paddingBottom: RFValue(4, 414),
    textAlign: "left",
  },
  rejectedHeader: {
    alignItems: "center",
    flex: 1,
  },
  rejectedOuterView: {
    // maxHeight: "40%",
    paddingHorizontal: "5%",
    marginTop: "5%",
  },
  contentStyle: {
    paddingBottom: RFValue(10, 414),
  },
  rejectReasonWord: {
    fontSize: RFValue(6, 414),
    // marginLeft: RFValue(5, 414),
    color: "#fff",
    textAlign: "center",
    textAlignVertical: "center",
  },
  rejectModalView: {
    // marginTop: "5%",
    // paddingHorizontal: RFValue(10, 414),
  },
  customButtonStyle: {
    width: RFValue(60, 414),
    height: RFValue(25, 414),
    alignSelf: "flex-end",
    marginHorizontal: RFValue(2, 414),
  },
  customButtonText: {
    fontSize: RFValue(7, 414),
    color: globalColors.white,
    // paddingVertical: 5
  },
  moveToWalletButton: {
    borderColor: "#fff",
    width: RFValue(90, 414),
    marginTop: RFValue(7.5, 414),
    marginRight: RFValue(10, 414),
  },
  rejectedButtonView: { display: "flex", flexDirection: "row" },
  reasonView: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: I18nManager.isRTL ? "row-reverse" : "row",
    marginVertical: RFValue(2.5, 414),
    width: "90%",
    alignSelf: "center",
    marginHorizontal: RFValue(7.5, 414),
  },
  modalView: { margin: 0 },
  reasonNumberView: {
    alignItems: "center",
    justifyContent: "center",
    width: RFValue(12.5, 414),
    height: RFValue(12.5, 414),
    textAlign: "center",
    borderRadius: RFValue(15, 414),
    marginRight: RFValue(2, 414),
    backgroundColor: globalColors.orange,
  },
  returnAmountWalletLinkText: {
    fontSize: RFValue(6, 414),
    color: globalColors.orange,
    textDecorationLine: "underline",
    textAlign: "center",
  },
  returnAmountWalletLinkView: {
    alignSelf: "center",
    paddingBottom: RFValue(10, 414),
  },
  updateAdButton: { alignSelf: "center", marginBottom: RFValue(10, 414) },
  dispalyBlock: {
    display: "flex",
    width: RFValue(5, 414),
    height: RFValue(5, 414),
    backgroundColor: "#EA514B",
    borderRadius: RFValue(10, 414),
    alignSelf: "center",
  },
  updateAdBrandButton: {
    alignSelf: "center",
    marginBottom: RFValue(10, 414),
    borderWidth: 1,
    borderColor: globalColors.white,
  },
  rejectedModalReasonBrandText: {
    textAlign: "center",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7.5, 414),
    color: "#fff",
    width: "90%",
    marginHorizontal: RFValue(1, 414),
    alignSelf: "center",
    // marginTop: 20,
  },
  brandRejection: {
    borderWidth: 1,
    marginVertical: RFValue(20, 414),
    // marginHorizontal: RFValue(20, 414),
    borderColor: globalColors.white,
    borderRadius: RFValue(10, 414),
    paddingTop: RFValue(10, 414),
    paddingHorizontal: RFValue(10, 414),
    width: "80%",
    alignSelf: "center",
  },
  buttonView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: RFValue(10, 414),
  },
});
