import { StyleSheet, PixelRatio } from "react-native";
import {
  widthPercentageToDP,
  heightPercentageToDP,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../../GlobalStyles";
export default StyleSheet.create({
  input1: {
    marginBottom: RFValue(15, 414),
    alignSelf: "center",
    width: 300,
    borderColor: "transparent",
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: RFValue(15, 414),
    paddingHorizontal: 15,
  },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    borderRadius: RFValue(15, 414),
    marginBottom: RFValue(-5, 414),
  },
  inputText: {
    fontFamily: "montserrat-regular",
    fontSize: 14 / PixelRatio.getFontScale(),
    color: "#fff",
    alignSelf: "center",
    // textAlign: "center",
    width: "100%",
    paddingVertical: RFValue(5, 414),
    borderBottomColor: "transparent",
    height: RFValue(25, 414),
  },
  labelView: {
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: 10,
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: 15,
    zIndex: 1,
  },
  toggleStyle: {
    width: widthPercentageToDP("13"),
    height: heightPercentageToDP("2.7"),
    borderRadius: 25,
    padding: 0,
  },
  toggleCircle: {
    width: widthPercentageToDP("5"),
    height: heightPercentageToDP("2.4"),
    borderRadius: 50,
  },
  membersTypes: {
    alignSelf: "flex-start",
    marginVertical: 10,
    width: "85%",
    flexDirection: "column",
    paddingHorizontal: 10,
  },
  memberTypeView: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginVertical: RFValue(5, 414),
  },
  meberTypeStyle: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    textAlign: "left",
    textTransform: "uppercase",
  },
  memberDescription: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    textAlign: "left",
  },
  deleteTeamMember: {
    marginBottom: RFValue(5, 414),
    width: "70%",
    height: RFValue(25, 414),
    borderRadius: RFValue(25, 414),
    backgroundColor: globalColors.orange,
    alignSelf: "center",
    justifyContent: "center",
  },
  deleteText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    textTransform: "uppercase",
    color: "#FFF",
    textAlign: "center",
  },
});
