import { StyleSheet, PixelRatio, I18nManager } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { isRTL } from "expo-localization";
import { globalColors } from "../../../GlobalStyles";
const styles = StyleSheet.create({
  safeAreaView: {
    // backgroundColor: "#0000",
    height: "100%",
    backgroundColor: globalColors.bluegem,
  },
  container: {
    backgroundColor: "transparent",
    flex: 1,
  },
  contentContainer: {
    // flexGrow: 1,
    flex: 1,
    // marginTop: hp(3),
    marginTop: 30,
    // justifyContent: 'space-between',
  },
  mainView: {
    // minHeight: 300,
    // flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  placeholder: {
    borderRadius: RFValue(15, 414),
    overflow: "hidden",
    alignSelf: "center",
    width: RFValue(125, 414),
    height: RFValue(125, 414),
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: globalColors.orange,
  },
  imagePlaceholder: {
    opacity: 0.5,
    // backgroundColor: 'rgba(0,0,0,0.5)',
    backgroundColor: "#000",
    borderRadius: 20,
    // overflow: 'hidden',
    alignSelf: "center",
    width: "100%",
    height: "100%",
    zIndex: 0,
    justifyContent: "center",
  },
  blankView: {
    backgroundColor: "rgba(0,0,0,0.5)",
    opacity: 0.4,
    height: "100%",
    width: "100%",
    flex: 1,
  },
  optionsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
    marginVertical: 20,
  },
  optionsRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    // paddingBottom: 20
  },
  inactivetext: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: "#fff",
    // paddingLeft: 10
  },
  activetext: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: "#FF9D00",
  },
  optionsIconSize: {
    fontSize: 25,
  },
  optionsTextContainer: {
    textAlign: "center",
    paddingLeft: 10,
  },
  inputContainer: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "center",
  },
  netLocStyle: {
    backgroundColor: "#5D1CD8",
    borderRadius: 10,
    // marginRight: 50,
    borderColor: "#5D1CD8",
    // width: "100%",
    width: wp(20),
    height: 50,
  },
  networkLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    textAlign: "center",
    color: "#fff",
    // flex: 1,
    // paddingLeft: 20,
    top: 2,
    // right: 4,
  },
  input: {
    // backgroundColor: '#5D1CD8',
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: 40,
    borderColor: "transparent",
    alignSelf: "center",
    height: 54,
    paddingHorizontal: 0,
    width: 300,
  },
  inputtext: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7 / PixelRatio.getFontScale(), 414),
    alignSelf: "center",
    textAlign: "center",
    color: "#FFF",
    borderColor: "transparent",
  },
  loadingSafeArea: {
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  uplaodPercentage: {
    fontSize: RFValue(8, 414),
    color: "#fff",
    fontFamily: "montserrat-bold",
    textAlign: "center",
    alignSelf: "center",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    top: "15%",
  },
  plaodPercentage: {
    fontSize: RFValue(8, 414),
    color: "#fff",
    fontFamily: "montserrat-bold",
    textAlign: "center",
    alignSelf: "center",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  uplaodText: {
    justifyContent: "center",
    fontSize: RFValue(6, 414),
    color: "white",
    fontFamily: "montserrat-medium",
    alignSelf: "center",
    paddingTop: 10,
    textAlign: "center",
  },
  footerTextStyle: {
    fontSize: RFValue(6, 414),
    color: "white",
    fontFamily: "montserrat-medium",
    alignSelf: "center",
  },
  footerStyle: {
    backgroundColor: "transparent",
    borderTopWidth: 0,
    elevation: 0,
    display: "flex",
    alignItems: "center",
    // flex: 1,
    justifyContent: "flex-end",
    paddingVertical: 10,
    // position: 'absolute',
    // bottom: 50,
  },
  footerButtonsContainer: {
    display: "flex",
    flexDirection: "row",
  },
  inputMiddleButton: {
    position: "absolute",
    backgroundColor: globalColors.orange,
    alignSelf: "center",
    width: RFValue(35, 414),
    height: RFValue(35, 414),
    borderRadius: 45,
    borderColor: "transparent",
    top: "50%",
    left: "50%",
    flexDirection: "column",
    opacity: 1,
    transform: [
      {
        translateX: I18nManager.isRTL ? 35 : -35,
      },
      {
        translateY: -40,
      },
    ],
  },
  inputMiddleButtonEdit: {
    position: "absolute",
    // backgroundColor: '#FF9D00',
    alignSelf: "center",
    width: RFValue(35, 414),
    height: RFValue(35, 414),
    borderRadius: RFValue(22.5, 414),
    borderColor: "transparent",
    top: "50%",
    left: "50%",
    flexDirection: "column",
    opacity: 1,
    alignItems: "center",
    transform: [
      {
        translateX: I18nManager.isRTL
          ? RFValue(17.5, 414)
          : RFValue(-17.5, 414),
      },
      {
        translateY: RFValue(-20, 414),
      },
    ],
  },
  icon: {
    color: "#fff",
    alignSelf: "center",
    justifyContent: "center",
    textAlign: "center",
    fontSize: RFValue(17.5, 414),
    paddingTop: RFValue(7.5, 414),
  },
  mediaButtonMsg: {
    alignSelf: "center",
    textAlign: "center",
    paddingTop: 23,
    fontFamily: "montserrat-medium",
    fontSize: RFValue(7, 414),
    width: RFValue(75, 414),
    color: globalColors.orange,
  },
  mediaButtonMsg1: {
    textAlign: "center",
    paddingTop: 5,
    fontFamily: "montserrat-medium",
    fontSize: RFValue(7, 414),
    width: RFValue(75, 414),
    color: globalColors.orange,
  },
  button: {
    width: wp(15),
    height: hp(7),
  },
  errorMsg: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-medium",
    fontSize: RFValue(6, 414),
    paddingTop: 10,
  },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    borderRadius: 30,
    marginBottom: -10,
  },
  topContainer: {
    paddingVertical: 30,
    width: 300,
    flexDirection: "row",
    alignSelf: "center",
    // shadowOffset: { width: 1, height: 1 },
    // shadowColor: 'black',
    // shadowOpacity: 0.2,
  },
  collectionAdLinkForm2: {
    borderTopStartRadius: 0,
    borderBottomStartRadius: 0,
    borderBottomEndRadius: 40,
    borderTopEndRadius: 40,
  },
  collectionAdLinkForm1: {
    borderBottomEndRadius: 0,
    borderTopEndRadius: 0,
    borderBottomStartRadius: 40,
    borderTopStartRadius: 40,
  },
  activeButton: {
    backgroundColor: "#FF9D00",
    height: 50,
    width: RFValue(75, 414),
    justifyContent: "center",
    flexDirection: "column",
  },
  inactiveText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
  },
  activeText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    color: "#fff",
    textAlign: "center",
  },
  button2: {
    backgroundColor: "rgba(0,0,0,0.2)",
    width: RFValue(75, 414),
    height: 50,
    justifyContent: "center",
    flexDirection: "column",
  },
  imageView: {
    backgroundColor: globalColors.orange,
    width: RFValue(62.5, 414),
    paddingVertical: RFValue(5, 414),
    borderRadius: RFValue(15, 414),
    marginBottom: RFValue(-10, 414),
    zIndex: 1,
  },
  productText: {
    textAlign: "center",
    color: "#FFF",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8.5, 414),
  },
  deepLinkLabelView: {
    borderTopLeftRadius: 150,
    borderTopRightRadius: 150,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    paddingTop: 8,
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: 15,
    zIndex: 1,
  },
  websiteView: {
    alignItems: "center",
    width: "100%",
  },
  websiteLabelView: {
    borderTopLeftRadius: 150,
    borderTopRightRadius: 150,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    paddingTop: 8,
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: 15,
    zIndex: 1,
  },
  uplaodPercentageText: {
    position: "absolute",
    fontFamily: "montserrat-bold",
    fontSize: 9,
    color: "#FFF",
    top: "35%",
    left: 17,
    textAlign: "center",
  },
});

export default styles;
