version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  deploy:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - aws-s3/sync:
          from: bucket
          to: 's3://ota.optimizeapp.com/prefix'
          overwrite: true
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
workflows:
  version: 2
  main:
    jobs:
      - deploy:
          context: aws-bh
          filters:
            branches:
              only: master-copy
