import { I18nManager, StyleSheet } from "react-native";
import { globalColors } from "../../../../GlobalStyles";

export default StyleSheet.create({
  adRejectedTitle: {
    fontSize: 18,
    fontFamily: "montserrat-bold",
    color: "#EA514B",
    textTransform: "uppercase",
    marginLeft: 4,
    // paddingVertical: 5,
  },
  rejectedReasonContainer: {
    backgroundColor: "#0005",
    borderRadius: 35,
    flexDirection: "column",
    // width: "95%",
    justifyContent: "space-evenly",
    // marginTop: 10,
  },
  reasonTitle: {
    // textAlign: "left",
    color: globalColors.orange,
    textTransform: "uppercase",
    fontFamily: "montserrat-bold-english",
    fontSize: 13,
    marginBottom: 5,
  },
  rejectedReasonText: {
    textAlign: "left",
    fontSize: 12,
    fontFamily: "montserrat-regular-english",
    color: "#fff",
    lineHeight: 16,
    // textTransform: "uppercase",
    marginLeft: 5,
  },
  rejectedModalTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "space-evenly",
    width: "75%",
  },
  rejectedModalReasonText: {
    textAlign: "left",
    fontFamily: "montserrat-regular-english",
    fontSize: 12,
    color: "#fff",
    marginHorizontal: 2,
  },
  rejectedModalReasonHeadText: {
    textAlign: "left",
    fontFamily: "montserrat-bold-english",
    fontSize: 14,
    color: "#fff",
    marginHorizontal: 2,
    textTransform: "uppercase",
  },
  rejectedInfoButton: {
    alignSelf: "flex-end",
    marginHorizontal: 20,
    marginBottom: 15,
  },
  rejectedReasonView: {
    paddingHorizontal: 20,
    paddingVertical: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
  },
  hereReasonsText: {
    fontSize: 14,
    fontFamily: "montserrat-regular",
    color: "#EA514B",
    paddingTop: 5,
    paddingHorizontal: 20,
    paddingBottom: 8,
    textAlign: "left",
  },
  rejectedHeader: {
    alignItems: "center",
    flex: 1,
  },
  rejectedOuterView: {
    // maxHeight: "40%",
    paddingHorizontal: "5%",
    marginTop: "5%",
  },
  contentStyle: {
    paddingBottom: 20,
  },
  rejectReasonWord: {
    fontSize: 12,
    // marginLeft: 10,
    color: "#fff",
    textAlign: "center",
    textAlignVertical: "center",
  },
  rejectModalView: {
    // marginTop: "5%",
    // paddingHorizontal: 20,
  },
  customButtonStyle: {
    width: 120,
    height: 50,
    alignSelf: "flex-end",
    marginHorizontal: 4,
  },
  customButtonText: {
    fontSize: 14,
    color: globalColors.white,
    // paddingVertical: 5
  },
  moveToWalletButton: {
    borderColor: "#fff",
    width: 180,
    marginTop: 15,
    marginRight: 20,
  },
  rejectedButtonView: { display: "flex", flexDirection: "row" },
  reasonView: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: I18nManager.isRTL ? "row-reverse" : "row",
    marginVertical: 5,
    width: "90%",
    alignSelf: "center",
    marginHorizontal: 15,
  },
  modalView: { margin: 0 },
  reasonNumberView: {
    alignItems: "center",
    justifyContent: "center",
    width: 25,
    height: 25,
    textAlign: "center",
    borderRadius: 30,
    marginRight: 4,
    backgroundColor: globalColors.orange,
  },
  returnAmountWalletLinkText: {
    fontSize: 12,
    color: globalColors.orange,
    textDecorationLine: "underline",
    textAlign: "center",
  },
  returnAmountWalletLinkView: {
    alignSelf: "center",
    paddingVertical: 20,
  },
  updateAdButton: { alignSelf: "center" },
  displayBlock: {
    display: "flex",
    width: 10,
    height: 10,
    backgroundColor: "#EA514B",
    borderRadius: 20,
    alignSelf: "center",
  },
  adRejetcedHeader: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  rejectedDetailView: {
    width: "100%",
    backgroundColor: "#0005",
    borderRadius: 35,
    paddingBottom: 20,
  },
});
