import { StyleSheet } from "react-native";
import { heightPercentageToDP as hp } from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    top: hp("10"),
    alignItems: "center",
    flexDirection: "column",
    opacity: 1,
    elevation: 0,
    marginLeft: 0,
    marginRight: 0,
  },
  headerContainer: {
    justifyContent: "flex-start",
    marginTop: RFValue(5, 414),
    alignItems: "center",
  },
  transactionFilterContainer: {
    justifyContent: "space-between",
  },
  title: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    width: RFValue(75, 414),
    paddingTop: RFValue(10, 414),
    alignSelf: "center",
  },
  titleStatus: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    width: RFValue(75, 414),
    paddingTop: RFValue(10, 414),
    alignSelf: "center",
    paddingBottom: RFValue(10, 414),
  },
  titleDate: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    marginBottom: RFValue(-5, 414),
    alignSelf: "center",
  },
  labelView: {
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: 0,
    marginTop: RFValue(10, 414),
    zIndex: 1,
  },
  subtext: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    paddingTop: RFValue(12.5, 414),
    color: "#fff",
    textAlign: "center",
  },
  clearFilterText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    paddingTop: RFValue(12.5, 414),
    color: "#fff",
    textAlign: "center",
    textDecorationLine: "underline",
    marginBottom: RFValue(10, 414),
    textDecorationColor: "#fff",
  },
  dateInput: {
    marginBottom: RFValue(7.5, 414),
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: RFValue(20, 414),
    alignSelf: "center",
    width: RFValue(165, 414),
    height: hp(7.9),
    justifyContent: "center",
  },
  categories: {
    textAlign: "center",
    color: "#fff",
    flexDirection: "column",
    fontFamily: "montserrat-regular",
    fontSize: RFValue(8, 414),
    paddingHorizontal: RFValue(5, 414),
  },
  numbers: {
    textAlign: "center",
    color: "#FF9D00",
    fontFamily: "montserrat-medium",
    fontSize: RFValue(8, 414),
    paddingHorizontal: RFValue(5, 414),
  },
  dateContainer: {
    flexDirection: "row",
    justifyContent: "center",
  },
  startColumn: {
    flexDirection: "column",
    // alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  middleColumn: {
    flexDirection: "column",
    justifyContent: "center",
  },
  endColumn: {
    flexDirection: "column",
    justifyContent: "center",
  },
  bottomView: {
    bottom: "10%",
  },
  fontSize12: {
    fontSize: RFValue(6, 414),
  },
});

export default styles;
