import {
  StyleSheet,
  PixelRatio,
  I18nManager,
  Platform,
  StatusBar,
} from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { globalColors } from "../../../../GlobalStyles";
const STATUSBAR_HEIGHT = Platform.OS === "ios" ? 35 : StatusBar.currentHeight;

export const colors = {
  black: "#1a1917",
  gray: "#888888",
  background1: "#751AFF",
  background2: "#6268FF",
};
const styles = StyleSheet.create({
  safeAreaView: { backgroundColor: "#fff" },
  container: {
    // backgroundColor: "#0000",
    backgroundColor: globalColors.bluegem,
    display: "flex",
    justifyContent: "space-between",
    top: RFValue(5, 414),
    // zIndex: 5
  },
  backDrop: {
    position: "absolute",
    top: hp(5) < 30 ? -hp("73%") : -hp("63%"),
    alignSelf: "center",
  },
  block1: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    width: wp(100),
    paddingTop: RFValue(5, 414),
    zIndex: 1,
  },
  phoneicon: {
    alignSelf: "center",
    // marginTop: 20
  },
  mainContent: {
    // flex: 1,
    justifyContent: "space-evenly",
    paddingHorizontal: 26,
    paddingBottom: hp(14),
    paddingTop: RFValue(10, 414),
  },
  scrollViewStyle: {
    marginTop: RFValue(7.5, 414),
    zIndex: 2,
  },
  input1: {
    marginBottom: RFValue(15, 414),
    // borderRadius: RFValue(7.5, 414),
    alignSelf: "center",
    width: 300,
    // height: RFValue(15, 414),
    borderColor: "transparent",
    // backgroundColor: '#751AFF',
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: RFValue(15, 414),
  },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414) / PixelRatio.getFontScale(),
    color: "#fff",
    alignSelf: "flex-start",
    textAlign: I18nManager.isRTL ? "right" : "left",
    // marginBottom: -20,
    textTransform: "uppercase",
    marginTop: RFValue(5, 414),
  },
  inputText: {
    fontFamily: "montserrat-regular",
    fontSize: 14 / PixelRatio.getFontScale(),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
    paddingVertical: RFValue(5, 414),
    borderBottomColor: "transparent",
    height: RFValue(25, 414),
  },
  minBudget: {
    color: "#fff",
    alignSelf: "center",
    fontSize: RFValue(5.5, 414),
    fontFamily: "montserrat-regular",
  },
  title: {
    fontSize: 16,
    color: "#fff",
    textAlign: "center",
    fontFamily: "montserrat-bold",
    paddingTop: RFValue(15, 414),
  },
  input2: {
    paddingHorizontal: RFValue(25, 414),
    borderRadius: RFValue(15, 414),
    alignSelf: "center",
    top: RFValue(10, 414),
    borderColor: "transparent",
  },
  label: {
    fontFamily: "montserrat-regular",
    fontSize: 14,
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
  },
  downicon: {
    color: "#fff",
    fontSize: RFValue(10, 414),
  },
  popupOverlay: {
    height: "100%",
    overflow: "visible",
  },
  contentContainer: {
    marginTop: RFValue(5, 414),
    paddingTop: RFValue(7.5, 414),
    marginBottom: RFValue(7.5, 414),
    paddingBottom: RFValue(50, 414),
  },
  dateInput: {
    marginBottom: RFValue(2.5, 414),
    backgroundColor: "rgba(0,0,0,0.16)",
    borderRadius: RFValue(15, 414),
    alignSelf: "center",
    width: "100%",
    // width: 300,
    height: RFValue(27, 414),
    justifyContent: "center",
    // borderWidth: 0.5,
  },
  dateLabel: {
    textAlign: "left",
    color: globalColors.orange,
    flexDirection: "column",
    fontFamily: "montserrat-light",
    fontSize: RFValue(6, 414),
    // paddingHorizontal: 10
  },
  date: {
    fontFamily: "montserrat-bold-english",
    color: globalColors.orange,
    alignItems: "center",
    fontSize: RFValue(7, 414),
  },
  block1Title: {
    top: hp(5),
  },
  innerBlock1: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  dateContainer: {
    flexDirection: "row",
    // justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: RFValue(10, 414),
  },
  dateColumn: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  topContainer: {
    paddingVertical: RFValue(5, 414),
    width: RFValue(150, 414),
    flexDirection: "row",
    alignSelf: "center",
    // shadowOffset: { width: 1, height: 1 },
    // shadowColor: 'black',
    // shadowOpacity: 0.2,
  },
  collectionAdLinkForm2: {
    borderTopStartRadius: 0,
    borderBottomStartRadius: 0,
    borderBottomEndRadius: 40,
    borderTopEndRadius: 40,
  },
  collectionAdLinkForm1: {
    borderBottomEndRadius: 0,
    borderTopEndRadius: 0,
    borderBottomStartRadius: 40,
    borderTopStartRadius: 40,
  },
  button: {
    backgroundColor: "rgba(0,0,0,0.2)",
    width: RFValue(75, 414),
    height: RFValue(35, 414),
    justifyContent: "center",
    flexDirection: "column",
    marginHorizontal: 0,
  },
  activeButton: {
    // backgroundColor: "#FF9D00",
    height: RFValue(35, 414),
    width: RFValue(75, 414),
    justifyContent: "center",
    flexDirection: "column",
    marginHorizontal: 0,
  },
  inactiveText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    textTransform: "uppercase",
  },
  activeText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    color: "#fff",
    textAlign: "center",
    textTransform: "uppercase",
  },
  buttonSubText: {
    fontFamily: "montserrat-regular",
    paddingTop: 2,
    fontSize: RFValue(6, 414),
    textTransform: "none",
  },
  dateTextLabel: {
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  objectiveTextLabel: {
    marginTop: RFValue(15, 414),
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  collectionAdView: {
    paddingTop: RFValue(5, 414),
  },
  collectionAdText: {
    color: "#FFFFFF",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold",
    textAlign: "center",
    textTransform: "uppercase",
  },
  proceedButtonRTL: {
    width: RFValue(32.5, 414),
    height: RFValue(32.5, 414),
    // padding: 20
  },
  objectiveModal: {
    height: "76%",
    top: "5%",
    backgroundColor: "#fff",
    paddingTop: RFValue(5, 414),
    overflow: "hidden",
    borderRadius: RFValue(25, 414),
    width: "100%",
    alignSelf: "center",
  },
  customHeaderContainer: {
    height: RFValue(15, 414),
    justifyContent: "center",
    paddingHorizontal: RFValue(15, 414),
    paddingTop: RFValue(10, 414),
  },
  minDurationText: {
    color: "#FFF",
    textAlign: "center",
    marginTop: RFValue(-10, 414),
    marginBottom: RFValue(7.5, 414),
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6, 414),
  },
  statusBar: {
    height: STATUSBAR_HEIGHT,
  },
  questionIconContainer: {
    position: "absolute",
    right: "5%",
    bottom: "10%",
    zIndex: RFValue(5, 414),
  },
});

export default styles;
