platform :ios, '11.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'OptimizeApp' do
  rnPrefix = "../node_modules/react-native"
  pod 'react-native-ffmpeg/https-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Other native modules

  # Automatically detect installed unimodules
  use_unimodules!

  # react-native-cli autolinking
  # pod 'react-native-ffmpeg', :path => '../node_modules/react-native-ffmpeg'
  pod 'react-native-ffmpeg/https-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

   # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps', '3.5.0'
  pod 'Google-Maps-iOS-Utils', '2.1.0'


  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNAnalyticsIntegration-Mixpanel', :path => '../node_modules/@segment/analytics-react-native-mixpanel'

  pod 'RNVideoEditorSDK', :path => '../node_modules/react-native-videoeditorsdk'

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  pod 'RNPhotoEditorSDK', :path => '../node_modules/react-native-photoeditorsdk'

  # pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'
  pod "Segment-Adjust"
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'

  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'


  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10'
    end
  end
end