//Auth Types
export const SEND_MOBILE_NUMBER = "SEND_MOBILE_NUMBER";
export const VERIFY_MOBILE_NUMBER = "VERIFY_MOBILE_NUMBER";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const LOGOUT_USER = "LOGOUT_USER";
export const CREATE_AD_ACCOUNT = "CREATE_AD_ACCOUNT";
export const SET_BUSINESS_ACCOUNTS = "SET_BUSINESS_ACCOUNTS";
export const ADD_BUSINESS_ACCOUNT = "ADD_BUSINESS_ACCOUNT";
export const SET_CAMPAIGN_LIST = "SET_CAMPAIGN_LIST";
export const SET_CAMPAIGN = "SET_CAMPAIGN";
//Campaign Action Types
export const SET_AD_TYPE = "SET_AD_TYPE";
export const SET_AD_OBJECTIVE = "SET_AD_OBJECTIVE";
export const SET_AD_DESIGN = "SER_AD_DESIGN";
export const SET_AD_DETAILS = "SET_AD_DETAILS";
