//Auth Types
export const SEND_MOBILE_NUMBER = "SEND_MOBILE_NUMBER";
export const RESET_MESSAGE = "RESET_MESSAGE";
export const VERIFY_MOBILE_NUMBER = "VERIFY_MOBILE_NUMBER";
export const RESEND_VERIFICATION = "RESEND_VERIFICATION";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const ADD_ADDRESS = "ADD_ADDRESS";

export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_BUSINESSNAME = "VERIFY_BUSINESSNAME";
export const LOGOUT_USER = "LOGOUT_USER";
export const CREATE_AD_ACCOUNT = "CREATE_AD_ACCOUNT";
export const SET_BUSINESS_ACCOUNTS = "SET_BUSINESS_ACCOUNTS";
export const SET_CURRENT_BUSINESS_ACCOUNT = "SET_CURRENT_BUSINESS_ACCOUNT";
export const ADD_BUSINESS_ACCOUNT = "ADD_BUSINESS_ACCOUNT";
export const SET_CAMPAIGN_LIST = "SET_CAMPAIGN_LIST";
export const SET_CAMPAIGN = "SET_CAMPAIGN";
export const RESET_REGISTER = "RESET_REGISTER";
export const SET_LOADING = "SET_LOADING";

//Campaign Action Types
export const SET_AD_TYPE = "SET_AD_TYPE";
export const SET_AD_OBJECTIVE = "SET_AD_OBJECTIVE";
export const SET_AD_DESIGN = "SER_AD_DESIGN";
export const SET_AD_DETAILS = "SET_AD_DETAILS";
export const UPDATE_CAMPAIGN_DETAILS = "UPDATE_CAMPAIGN_DETAILS";
export const UPDATE_CAMPAIGN_LIST = "UPDATE_CAMPAIGN_LIST";
export const FILTER_CAMPAIGNS = "FILTER_CAMPAIGNS";
export const SET_SNAP_AUDIENCE_SIZE = "SET_SNAP_AUDIENCE_SIZE";
export const SET_SNAP_TOTAL_AUDIENCE_SIZE = "SET_SNAP_TOTAL_AUDIENCE_SIZE";
export const SET_INTERESTS = "SET_INTERESTS";
export const GOT_ALL_CAMPAIGNS = "GOT_ALL_CAMPAIGNS";
export const UPDATE_CAMPAIGN_STATUS = "UPDATE_CAMPAIGN_STATUS";
export const SET_AD_LOADING = "SET_AD_LOADING";
export const PAYMENT_REQUEST_URL = "PAYMENT_REQUEST_URL";

//Transaction Action Types
export const SET_TRAN_LOADING = "SET_TRAN_LOADING";
export const SET_TRANSACTION_LIST = "SET_TRANSACTION_LIST";
export const FILTER_TRANSACTION = "FILTER_TRANSACTION";
