//Login Types
export const SET_PUSH_NOTIFICATION_TOKEN = 'SET_PUSH_NOTIFICATION_TOKEN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ERROR_SET_PUSH_NOTIFICATION_TOKEN = 'ERROR_SET_PUSH_NOTIFICATION_TOKEN';
export const SET_LOADING_USER = 'SET_LOADING_USER';
export const SET_BASEURL = 'SET_BASEURL';

//Registeration Types
export const SET_INVITE_CODE = 'SET_INVITE_CODE';
export const SEND_MOBILE_NUMBER = 'SEND_MOBILE_NUMBER';
export const VERIFY_MOBILE_NUMBER = 'VERIFY_MOBILE_NUMBER';
export const RESEND_VERIFICATION = 'RESEND_VERIFICATION';
export const RESEND_VERIFICATION_EMAIL = 'RESEND_VERIFICATION_EMAIL';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_BUSINESSNAME = 'VERIFY_BUSINESSNAME';
export const RESET_REGISTER = 'RESET_REGISTER'; // NOT USED
export const ERROR_SET_INVITE_CODE = 'ERROR_SET_INVITE_CODE';
export const ERROR_SEND_MOBILE_NUMBER = 'ERROR_SEND_MOBILE_NUMBER';
export const ERROR_VERIFY_MOBILE_NUMBER = 'ERROR_VERIFY_MOBILE_NUMBER';
export const ERROR_RESEND_VERIFICATION = 'ERROR_RESEND_VERIFICATION';
export const ERROR_RESEND_VERIFICATION_EMAIL = 'ERROR_RESEND_VERIFICATION_EMAIL';
export const ERROR_SIGN_UP_USER = 'ERROR_SIGN_UP_USER';
export const ERROR_VERIFY_EMAIL = 'ERROR_VERIFY_EMAIL';
export const ERROR_VERIFY_BUSINESSNAME = 'ERROR_VERIFY_BUSINESSNAME';

//Account Managment
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const SET_LOADING_ACCOUNT_UPDATE = 'SET_LOADING_ACCOUNT_UPDATE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const CREATE_SNAPCHAT_AD_ACCOUNT = 'CREATE_SNAPCHAT_AD_ACCOUNT';
export const SET_BUSINESS_ACCOUNTS = 'SET_BUSINESS_ACCOUNTS';
export const SET_CURRENT_BUSINESS_ACCOUNT = 'SET_CURRENT_BUSINESS_ACCOUNT';
export const ADD_BUSINESS_ACCOUNT = 'ADD_BUSINESS_ACCOUNT';
export const GET_BILLING_ADDRESS = 'GET_BILLING_ADDRESS';
export const SET_BILLING_ADDRESS_LOADING = 'SET_BILLING_ADDRESS_LOADING';
export const ERROR_ADD_BUSINESS_ACCOUNT = 'ERROR_ADD_BUSINESS_ACCOUNT';
export const ERROR_SET_BUSINESS_ACCOUNTS = 'ERROR_SET_BUSINESS_ACCOUNTS';
export const ERROR_CHANGE_PASSWORD = 'ERROR_CHANGE_PASSWORD';
export const ERROR_ADD_ADDRESS = 'ERROR_ADD_ADDRESS';
export const ERROR_GET_BILLING_ADDRESS = 'ERROR_GET_BILLING_ADDRESS';
export const ERROR_CREATE_SNAPCHAT_AD_ACCOUNT = 'ERROR_CREATE_SNAPCHAT_AD_ACCOUNT';
export const ERROR_SET_CURRENT_BUSINESS_ACCOUNT = 'ERROR_SET_CURRENT_BUSINESS_ACCOUNT';
export const SET_LOADING_BUSINESS_LIST = 'SET_LOADING_BUSINESS_LIST';
export const GET_BILLING_ADDRESS_LOADING = 'GET_BILLING_ADDRESS_LOADING';

//Dashboard
export const SET_CAMPAIGN_LIST = 'SET_CAMPAIGN_LIST';
export const ERROR_SET_CAMPAIGN_LIST = 'ERROR_SET_CAMPAIGN_LIST';

export const SET_CAMPAIGN = 'SET_CAMPAIGN';
export const SET_CAMPAIGN_STATS = 'SET_CAMPAIGN_STATS';
export const SET_STATS_LOADING = 'SET_STATS_LOADING';

export const ERROR_SET_CAMPAIGN = 'ERROR_SET_CAMPAIGN';

export const GOT_ALL_CAMPAIGNS = 'GOT_ALL_CAMPAIGNS';

export const UPDATE_CAMPAIGN_LIST = 'UPDATE_CAMPAIGN_LIST';
export const ERROR_UPDATE_CAMPAIGN_LIST = 'ERROR_UPDATE_CAMPAIGN_LIST';

export const FILTER_CAMPAIGNS = 'FILTER_CAMPAIGNS';
export const VERIFY_BUSINESSURL = 'VERIFY_BUSINESSURL';
export const SET_REJECTED_STORYADS = 'SET_REJECTED_STORYADS';
export const SET_REJECTED_COLLECTIONADS = 'SET_REJECTED_COLLECTIONADS';
export const SET_REJECTED_ADTYPE = 'SET_REJECTED_ADTYPE';

//Logout Types
export const CLEAR_PUSH_NOTIFICATION_TOKEN = 'CLEAR_PUSH_NOTIFICATION_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';

//Loading Types
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_ACCOUNT_MANAGEMENT = 'SET_LOADING_ACCOUNT_MANAGEMENT';
export const SET_AD_LOADING = 'SET_AD_LOADING';
export const SET_AD_LOADING_OBJ = 'SET_AD_LOADING_OBJ';
export const SET_AD_LOADING_DETAIL = 'SET_AD_LOADING_DETAIL';
export const SET_AD_LOADING_DESIGN = 'SET_AD_LOADING_DESIGN';

//Campaign Action Types
export const RESET_CAMPAING_INFO = 'RESET_CAMPAING_INFO';
export const SET_AD_TYPE = 'SET_AD_TYPE';
export const SET_COLLECTION_AD_LINK_FORM = 'SET_COLLECTION_AD_LINK_FORM';
export const SET_AD_LOADING_COLLECTION_MEDIA = 'SET_AD_LOADING_COLLECTION_MEDIA';
export const SET_AD_COLLECTION_MEDIA = 'SET_AD_COLLECTION_MEDIA';
export const ERROR_SET_AD_COLLECTION_MEDIA = 'ERROR_SET_AD_COLLECTION_MEDIA';
export const RESET_COLLECTIONS = 'RESET_COLLECTIONS';

export const SET_AD_OBJECTIVE = 'SET_AD_OBJECTIVE';
export const SET_MINIMUN_CASH = 'SET_MINIMUN_CASH';
export const ERROR_SET_AD_OBJECTIVE = 'ERROR_SET_AD_OBJECTIVE';

export const SET_AD_DESIGN = 'SET_AD_DESIGN';
export const SET_STORYADCARD_LOADING_DESIGN = 'SET_STORYADCARD_LOADING_DESIGN';
export const SET_STORYADMEDIA_DESIGN = 'SET_STORYADMEDIA_DESIGN';
export const SET_STORYADMEDIA_DESIGN_UPLOADED = 'SET_STORYADMEDIA_DESIGN_UPLOADED';

export const ADD_SNAP_CARD = 'ADD_SNAP_CARD';
export const REMOVE_SNAP_CARD = 'REMOVE_SNAP_CARD';

export const SET_DELETE_CARD_LOADING = 'SET_DELETE_CARD_LOADING';
export const DELETE_STORY_AD_CARD = 'DELETE_STORY_AD_CARD';
export const SET_COVER_LOADING_DESIGN = 'SET_COVER_LOADING_DESIGN';
export const SET_COVER_DESIGN = 'SET_COVER_DESIGN';
export const ERROR_SET_COVER_DESIGN = 'ERROR_SET_COVER_DESIGN';

export const SAVE_CAMPAIGN_INFO = 'SAVE_CAMPAIGN_INFO';
export const HANDLE_STORY_VIDEO = 'HANDLE_STORY_VIDEO';
export const GET_VIDEO_URL_LOADING = 'GET_VIDEO_URL_LOADING';

export const SET_VIDEO_URL = 'SET_VIDEO_URL';
export const ERROR_SET_AD_DESIGN = 'ERROR_SET_AD_DESIGN';
export const SET_AD_DETAILS = 'SET_AD_DETAILS';
export const ERROR_SET_AD_DETAILS = 'ERROR_SET_AD_DETAILS';
export const UPDATE_CAMPAIGN_DETAILS = 'UPDATE_CAMPAIGN_DETAILS';
export const END_CAMPAIGN = 'END_CAMPAIGN';
export const ERROR_UPDATE_CAMPAIGN_DETAILS = 'ERROR_UPDATE_CAMPAIGN_DETAILS';
export const SET_SNAP_AUDIENCE_SIZE = 'SET_SNAP_AUDIENCE_SIZE';
export const ERROR_SET_SNAP_AUDIENCE_SIZE = 'ERROR_SET_SNAP_AUDIENCE_SIZE';
export const SET_SNAP_TOTAL_AUDIENCE_SIZE = 'SET_SNAP_TOTAL_AUDIENCE_SIZE';
export const ERROR_SET_SNAP_TOTAL_AUDIENCE_SIZE = 'ERROR_SET_SNAP_TOTAL_AUDIENCE_SIZE';

export const SET_LANGUAGE_LIST = 'SET_LANGUAGE_LIST';
export const ERROR_SET_LANGUAGE_LIST = 'ERROR_SET_LANGUAGE_LIST';

export const SET_INTERESTS = 'SET_INTERESTS';
export const ERROR_SET_INTERESTS = 'ERROR_SET_INTERESTS';

export const SET_DEVICE_MAKES = 'SET_DEVICE_MAKES';
export const ERROR_SET_DEVICE_MAKES = 'ERROR_SET_DEVICE_MAKES';

export const SET_IOS_VERSIONS = 'SET_IOS_VERSIONS';
export const ERROR_SET_IOS_VERSIONS = 'ERROR_SET_IOS_VERSIONS';

export const SET_ANDROID_VERSIONS = 'SET_ANDROID_VERSIONS';
export const ERROR_SET_ANDROID_VERSIONS = 'ERROR_SET_ANDROID_VERSIONS';

export const UPDATE_CAMPAIGN_STATUS = 'UPDATE_CAMPAIGN_STATUS'; //Not used yet

export const PAYMENT_REQUEST_URL = 'PAYMENT_REQUEST_URL';
export const ERROR_PAYMENT_REQUEST_URL = 'ERROR_PAYMENT_REQUEST_URL';
export const SET_INSTAGRAM_POST = 'SET_INSTAGRAM_POST';
export const ERROR_GET_INSTAGRAM_POST = 'ERROR_GET_INSTAGRAM_POST';
export const SET_INSTAGRAM_POST_LOADING = 'SET_INSTAGRAM_POST_LOADING';
export const SAVE_WEB_PRODUCTS_LOADING = 'SAVE_WEB_PRODUCTS_LOADING';
export const SUCCESS_SAVE_WEB_PRODUCTS = 'SUCCESS_SAVE_WEB_PRODUCTS';
export const ERROR_SAVE_WEB_PRODUCTS = 'ERROR_SAVE_WEB_PRODUCTS';
export const GET_WEB_PRODUCTS = 'GET_WEB_PRODUCTS';
export const ERROR_GET_WEB_PRODUCTS = 'ERROR_GET_WEB_PRODUCTS';
export const GET_WEB_PRODUCTS_LOADING = 'GET_WEB_PRODUCTS_LOADING';
export const STORYAD_ATTACHMENT = "STORYAD_ATTACHMENT";


//Transaction Action Types
export const SET_TRAN_LOADING = 'SET_TRAN_LOADING';
export const SET_TRANSACTION_LIST = 'SET_TRANSACTION_LIST';
export const FILTER_TRANSACTION = 'FILTER_TRANSACTION';
export const SET_WALLET_AMOUNT = 'SET_WALLET_AMOUNT';
export const ADD_WALLET_AMOUNT = 'ADD_WALLET_AMOUNT';
export const GET_WALLET_AMOUNT_IN_KWD = 'GET_WALLET_AMOUNT_IN_KWD';
export const USE_WALLET_AMOUNT = 'USE_WALLET_AMOUNT';
export const REMOVE_WALLET_AMOUNT = 'REMOVE_WALLET_AMOUNT';
export const CHECKOUT_WITH_WALLET = 'CHECKOUT_WITH_WALLET';
export const ERROR_SET_TRANSACTION_LIST = 'ERROR_SET_TRANSACTION_LIST';
export const ERROR_FILTER_TRANSACTION = 'ERROR_FILTER_TRANSACTION';
export const ERROR_SET_WALLET_AMOUNT = 'ERROR_SET_WALLET_AMOUNT';
export const ERROR_ADD_WALLET_AMOUNT = 'ERROR_ADD_WALLET_AMOUNT';
export const ERROR_GET_WALLET_AMOUNT_IN_KWD = 'ERROR_GET_WALLET_AMOUNT_IN_KWD';
export const ERROR_USE_WALLET_AMOUNT = 'ERROR_USE_WALLET_AMOUNT';
export const ERROR_REMOVE_WALLET_AMOUNT = 'ERROR_REMOVE_WALLET_AMOUNT';
export const ERROR_CHECKOUT_WITH_WALLET = 'ERROR_CHECKOUT_WITH_WALLET';

//Messenger Action Types
export const SET_CURRENT_MESSENGER = 'SET_CURRENT_MESSENGER';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const SET_AS_SEEN = 'SET_AS_SEEN';
export const UPDATE_LAST_SEEN = 'UPDATE_LAST_SEEN';
export const SET_LOADING_MESSENGER = 'SET_LOADING_MESSENGER';
export const SET_LOADING_MESSAGE = 'SET_LOADING_MESSAGE';
export const SET_UNSEEN_YET = 'SET_UNSEEN_YET';
export const SET_LOADING_CON = 'SET_LOADING_CON';
export const SET_AS_SUBSCRIBED = 'SET_AS_SUBSCRIBED';
export const SET_CONVERSATION_AS_OPEN = 'SET_CONVERSATION_AS_OPEN';
