# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: 'appstore', readonly: true)
    increment_build_number(xcodeproj: "OptimizeApp.xcodeproj")
    build_app(workspace: "OptimizeApp.xcworkspace", scheme: "OptimizeApp",
      clean: true,
    )
    #sentry_upload_dsym(
    #  auth_token: 'cea83a7cc6f54a4b8a67f3db6a1ad43951b1145659c444f8b0f3931ec6e914c1',
    #  org_slug: 'optimize',
    #  project_slug: 'optimizeapp',
    #)
    upload_to_testflight
  end
end
