export let getBusinessesResponseSuccess = {
  api_version: "v1",
  success: true,
  message: "User Business",
  data: [
    {
      id: 8,
      name: "New Business 1",
      country: {
        id: 2,
        name: "Kuwait",
      },
      type: "Agency",
      category: "Other",
      approval_status: 1,
      snap_terms: 0,
      fb_connected: 0,
      instagram_handle: null,
      business_website: null,
      snap_ad_account_id: "TEMP-SNAP-ADACCOUNT-ID",
      fb_ad_account_id: "TEMP-FB-ADACCOUNT-ID",
      walletamount: "0.00",
    },
    {
      id: 9,
      name: "New Business 2",
      country: {
        id: 3,
        name: "UAE",
      },
      type: "SME or Startup",
      category: "Other",
      approval_status: 0,
      snap_terms: 0,
      fb_connected: 0,
      instagram_handle: null,
      business_website: null,
      snap_ad_account_id: "TEMP-SNAP-ADACCOUNT-ID",
      fb_ad_account_id: "TEMP-FB-ADACCOUNT-ID",
      walletamount: "0.00",
    },
    {
      id: 10,
      name: "OP Business",
      country: {
        id: 3,
        name: "UAE",
      },
      type: "SME or Startup",
      category: "Other",
      approval_status: 0,
      snap_terms: 1,
      fb_connected: 0,
      instagram_handle: null,
      business_website: null,
      snap_ad_account_id: "TEMP-SNAP-ADACCOUNT-ID",
      fb_ad_account_id: "TEMP-FB-ADACCOUNT-ID",
      walletamount: "0.00",
    },
    {
      id: 11,
      name: "OP Business ssd",
      country: {
        id: 3,
        name: "UAE",
      },
      type: "SME or Startup",
      category: "Other",
      approval_status: 0,
      snap_terms: 0,
      fb_connected: 0,
      instagram_handle: null,
      business_website: null,
      snap_ad_account_id: "TEMP-SNAP-ADACCOUNT-ID",
      fb_ad_account_id: "TEMP-FB-ADACCOUNT-ID",
      walletamount: "0.00",
    },
  ],
};
