import { StyleSheet, PixelRatio } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../../GlobalStyles";
const styles = StyleSheet.create({
  safeAreaView: {
    // backgroundColor: "#0000",
    backgroundColor: globalColors.bluegem,
    height: "100%",
  },
  container: {
    backgroundColor: "#0000",
    display: "flex",
    justifyContent: "space-between",
  },
  backDrop: {
    position: "absolute",
    top: hp(5) < 30 ? -hp("73%") : -hp("63%"),
    alignSelf: "center",
  },
  googleIcon: {
    alignSelf: "center",
  },
  mainContent: {
    paddingBottom: hp(35),
    paddingTop: 20,
    paddingHorizontal: 26,
  },
  scrollViewStyle: {
    marginTop: 15,
  },
  inputViewContainer: {
    borderTopLeftRadius: 150,
    borderTopRightRadius: 150,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 30,
    paddingTop: 5,
    width: 150,
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: 20,
    zIndex: 1,
  },
  input1: {
    marginBottom: 30,
    alignSelf: "center",
    width: 300,
    borderColor: "transparent",
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: 30,
  },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    borderRadius: RFValue(15, 414),
    marginBottom: 0,
    height: RFValue(10, 414),
  },
  inputText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
    paddingVertical: RFValue(5, 414),
    borderBottomColor: "transparent",
    height: RFValue(25, 414),
  },
  input2: {
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    paddingHorizontal: RFValue(25, 414),
    borderRadius: RFValue(15, 414),
    alignSelf: "center",
    width: RFValue(150, 414),
    height: RFValue(25, 414),
    marginBottom: RFValue(10, 414),
    borderColor: "transparent",
  },
  label: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
  },
  downicon: {
    color: "#fff",
    fontSize: RFValue(10, 414),
  },
  popupOverlay: {
    height: "100%",
  },
  topContainer: {
    paddingVertical: RFValue(5, 414),
    // width: 300,
    width: "100%",
    flexDirection: "row",
    alignSelf: "center",
  },
  choiceButtonRight: {
    borderTopStartRadius: 0,
    borderBottomStartRadius: 0,
    borderBottomEndRadius: RFValue(20, 414),
    borderTopEndRadius: RFValue(20, 414),
    width: "50%",
    height: RFValue(30, 414),
  },
  choiceButtonLeft: {
    borderBottomEndRadius: 0,
    borderTopEndRadius: 0,
    borderBottomStartRadius: RFValue(20, 414),
    borderTopStartRadius: RFValue(20, 414),
    width: "50%",

    height: RFValue(30, 414),
  },
  inactiveButton: {
    backgroundColor: "rgba(0,0,0,0.2)",
    justifyContent: "center",
    flexDirection: "column",
    marginHorizontal: 0,
  },
  activeButton: {
    // backgroundColor: "#FF9D00",
    marginHorizontal: 0,
    justifyContent: "center",
    flexDirection: "column",
  },
  inactiveText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    textTransform: "uppercase",
  },
  activeText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: "#fff",
    textAlign: "center",
    textTransform: "uppercase",
  },

  dateTextLabel: {
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  countryTextLabel: {
    marginTop: RFValue(15, 414),
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 441),
    zIndex: 1,
  },
  languageChoiceView: {
    paddingTop: RFValue(5, 414),
  },
  languageChoiceText: {
    color: "#FFFFFF",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold",
    textAlign: "center",
    textTransform: "uppercase",
  },
  proceedButtonRTL: {
    width: RFValue(27.5, 414),
    height: RFValue(27.5, 414),
  },
  minDurationText: {
    color: "#FFF",
    textAlign: "center",
    marginTop: RFValue(-10, 414),
    marginBottom: RFValue(7.5, 414),
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6, 414),
  },
});

export default styles;
