import { StyleSheet, PixelRatio, I18nManager } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
  heightPercentageToDP,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../../GlobalStyles";
export const colors = {
  black: "#1a1917",
  gray: "#888888",
  background1: "#751AFF",
  background2: "#6268FF",
};
const styles = StyleSheet.create({
  downIcon: {
    position: "absolute",
    right: RFValue(7.5, 414),
    color: globalColors.rum,
    width: RFValue(12.5, 414),
    height: RFValue(12.5, 414),
    fontSize: RFValue(15, 414),
    // marginVertical: 2,
    // bottom: RFValue(2.5, 414),
    alignSelf: "center",
  },
  swipeUpView: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: RFValue(5, 414),
    // width: wp(60),
    // marginHorizontal: RFValue(50, 414),
  },
  swipeUpText: {
    alignSelf: "flex-start",
    color: globalColors.rum,
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7.5, 414),
    textTransform: "uppercase",
  },
  swipeUpSubText: {
    fontSize: RFValue(6, 414),
    textAlign: "left",
    fontFamily: "montserrat-medium-english",
    color: globalColors.purple,
    width: "80%",
  },
  placeHolderStoryAd: {
    // height: hp(44),
    flex: 1,
    marginBottom: RFValue(50, 414),
  },
  transition: { height: "100%" },
  mainView: {
    marginHorizontal: RFValue(10, 414),
    backgroundColor: globalColors.transparent,
    height: "100%",
  },
  captionTextView: { flex: 1 },
  penIcon: { alignSelf: "center" },
  lowerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    // alignSelf: "flex-end",
    marginTop: RFValue(5, 414),
    marginHorizontal: RFValue(10, 414),
  },
  captionMainView: {
    height: hp(60),
    borderRadius: RFValue(25, 414),
    marginHorizontal: RFValue(20, 414),
    backgroundColor: "rgba(0,0,0,.3)",
    padding: RFValue(17.5, 414),
    marginBottom: RFValue(2.5, 414),
  },
  safeAreaView: {
    backgroundColor: "#0000",
    height: "100%",
  },
  container: {
    backgroundColor: "#0000",
    display: "flex",
    justifyContent: "space-between",
    // zIndex: 5
  },
  backDrop: {
    position: "absolute",
    top: hp(5) < 30 ? -hp("73%") : -hp("63%"),
    alignSelf: "center",
  },
  block1: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    width: wp(100),
    paddingTop: RFValue(5, 414),
    zIndex: 1,
  },
  phoneicon: {
    alignSelf: "center",
    // marginTop: 20
  },
  mainContent: {
    // flex: 1,
    // justifyContent: 'flex-start',
    paddingBottom: hp(14),
    paddingTop: RFValue(10, 414),
  },
  scrollViewStyle: {
    marginTop: RFValue(7.5, 414),
    zIndex: 2,
  },
  input1: {
    marginBottom: RFValue(15, 414),
    // borderRadius: RFValue(7.5, 414),
    alignSelf: "center",
    width: RFValue(150, 414),
    // height: RFValue(15, 414),
    borderColor: "transparent",
    // backgroundColor: '#751AFF',
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: RFValue(15, 414),
  },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    borderRadius: RFValue(15, 414),
    marginBottom: I18nManager.isRTL ? -16 : -10,
  },
  inputText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
    paddingVertical: RFValue(5, 414),
    borderBottomColor: "transparent",
    height: RFValue(25, 414),
  },
  minBudget: {
    color: "#fff",
    alignSelf: "center",
    fontSize: RFValue(5.5, 414),
    fontFamily: "montserrat-regular",
  },
  title: {
    fontSize: RFValue(8, 414),
    color: "#fff",
    textAlign: "center",
    fontFamily: "montserrat-bold",
    paddingTop: RFValue(15, 414),
  },
  input2: {
    paddingHorizontal: RFValue(25, 414),
    borderRadius: RFValue(15, 414),
    alignSelf: "center",
    top: RFValue(10, 414),
    borderColor: "transparent",
  },
  label: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(17, 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
  },
  downicon: {
    color: "#fff",
    fontSize: RFValue(10, 414),
  },
  popupOverlay: {
    height: "100%",
  },
  contentContainer: {
    marginTop: RFValue(7.5, 414),
    paddingTop: RFValue(7.5, 414),
    marginBottom: RFValue(7.5, 414),
  },
  dateInput: {
    marginBottom: RFValue(2.5, 414),
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: RFValue(15, 414),
    alignSelf: "center",
    width: RFValue(150, 414),
    height: RFValue(25, 414),
    justifyContent: "center",
    // borderWidth: 0.5,
  },
  dateLabel: {
    textAlign: "center",
    color: globalColors.orange,
    flexDirection: "column",
    fontFamily: "montserrat-regular",
    fontSize: RFValue(8, 414),
    // paddingHorizontal: 10
  },
  date: {
    fontFamily: "montserrat-bold",
    color: "#FF9D00",
    alignItems: "center",
    fontSize: RFValue(7, 414),
  },
  block1Title: {
    top: hp(5),
  },
  innerBlock1: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  dateContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  dateColumn: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  topContainer: {
    paddingVertical: RFValue(5, 414),
    width: RFValue(150, 414),
    flexDirection: "row",
    alignSelf: "center",
    // shadowOffset: { width: 1, height: 1 },
    // shadowColor: 'black',
    // shadowOpacity: 0.2,
  },
  collectionAdLinkForm2: {
    borderTopStartRadius: 0,
    borderBottomStartRadius: 0,
    borderBottomEndRadius: RFValue(20, 414),
    borderTopEndRadius: RFValue(20, 414),
  },
  collectionAdLinkForm1: {
    borderBottomEndRadius: 0,
    borderTopEndRadius: 0,
    borderBottomStartRadius: RFValue(20, 414),
    borderTopStartRadius: RFValue(20, 414),
  },
  button: {
    backgroundColor: "rgba(0,0,0,0.2)",
    width: RFValue(75, 414),
    height: RFValue(35, 414),
    justifyContent: "center",
    flexDirection: "column",
  },
  activeButton: {
    backgroundColor: "#FF9D00",
    height: RFValue(35, 414),
    width: RFValue(75, 414),
    justifyContent: "center",
    flexDirection: "column",
  },
  inactiveText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
  },
  activeText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    color: "#fff",
    textAlign: "center",
  },
  buttonSubText: {
    fontFamily: "montserrat-regular",
    paddingTop: 2,
    fontSize: RFValue(6, 414),
  },
  dateTextLabel: {
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  objectiveTextLabel: {
    marginTop: RFValue(15, 414),
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  collectionAdView: {
    paddingTop: RFValue(5, 414),
  },
  collectionAdText: {
    color: "#FFFFFF",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold",
    textAlign: "center",
  },
  proceedButtonRTL: {
    width: RFValue(32.5, 414),
    height: RFValue(32.5, 414),
    // padding: 20
  },
  adImageOptionView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderRadius: RFValue(25, 414),
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  adImageOptionButton: {
    width: "50%",
    height: RFValue(20, 414),
    marginHorizontal: 0,
  },
  outerBlock: {
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: RFValue(25, 414),
    marginTop: RFValue(6, 414),
    flex: 1,
  },
  profileBsnNameView: {
    display: "flex",
    flexDirection: "row",
    paddingVertical: RFValue(6, 414),
    paddingLeft: RFValue(6, 414),
    alignItems: "center",
  },
  businessProfilePic: {
    width: RFValue(27.5, 414),
    height: RFValue(27.5, 414),
    borderRadius: RFValue(15, 414),
  },
  bsnNameView: {
    paddingLeft: RFValue(6, 414),
  },
  businessNameText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(5.5, 414),
    color: globalColors.white,
    textAlign: "left",
  },
  businessName: {
    fontFamily: "montserrat-medium-english",
    fontSize: RFValue(8, 414),
    color: globalColors.white,
    textAlign: "left",
  },

  placeholder: {
    borderRadius: RFValue(15, 414),
    overflow: "hidden",
    alignSelf: "center",
    width: "90%",
    height: hp(5) < 40 ? hp(25) : hp(38),
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
  },

  placeholder1: {
    opacity: 0.35,
    borderRadius: RFValue(15, 414),
    overflow: "hidden",
    alignSelf: "center",
    width: "100%",
    height: "100%",
    zIndex: 0,
    position: "absolute",
    justifyContent: "center",
  },
  captionView: {
    display: "flex",
    flexDirection: "row",
    borderRadius: RFValue(15, 414),
    paddingHorizontal: RFValue(10, 414),
    paddingVertical: RFValue(5, 414),
    alignSelf: "center",
    width: "90%",
    // height: "100%",
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "space-between",
    marginTop: RFValue(5, 414),
    marginBottom: RFValue(35, 414),
  },
  captionText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(4.5, 414),
    color: globalColors.white,
    textAlign: "left",
  },
  caption: {
    fontFamily: "montserrat-medium",
    fontSize: RFValue(6, 414),
    color: globalColors.white,
    textAlign: "left",
  },
  destinationView: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: globalColors.white,
    paddingHorizontal: RFValue(10, 414),
    paddingVertical: RFValue(7.5, 414),
    borderRadius: RFValue(25, 414),
    marginTop: RFValue(7.5, 414),
    width: "100%",
    // height: "12%",
  },
  destinationText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: globalColors.orange,
    textTransform: "uppercase",
    marginTop: RFValue(2.5, 414),
  },
  captionTextBig: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    color: globalColors.white,
    textAlign: "left",
  },
  message: {
    flex: 1,
    textAlign: "left",
    // alignSelf: "flex-start",
    color: globalColors.white,
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-regular",
  },
  addMediaText: {
    fontSize: RFValue(5.5, 414),
    fontFamily: "montserrat-medium",
    textAlign: "center",
    textTransform: "uppercase",
    color: globalColors.orange,
    marginVertical: RFValue(2.5, 414),
  },
  websiteLink: {
    fontFamily: "montserrat-light-english",
    color: globalColors.purple,
    fontSize: RFValue(6, 414),
    textAlign: "center",
  },
  uplaodPercentageText: {
    position: "absolute",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(4, 414),
    color: "#FFF",
    top: "32%",
    left: "32%",
    textAlign: "center",
  },
  lowerBtnWidth: {
    width: "50%",
    height: RFValue(25, 414),
    marginHorizontal: RFValue(2.5, 414),
  },
  reviewButton: {
    alignSelf: "center",
    borderWidth: 1,
    borderColor: globalColors.white,
    width: "50%",
    height: RFValue(25, 414),
    marginHorizontal: 0,
  },
  uplaodPercentageText: {
    position: "absolute",
    fontFamily: "montserrat-bold-english",
    fontSize: RFValue(7, 414),
    lineHeight: RFValue(8, 414),
    color: "#FFF",
    top: hp(1.75),
    right: 0,
    left: 0,
    textAlign: "center",
  },
  uploadingText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    color: "#FFF",
    textTransform: "uppercase",
    marginHorizontal: RFValue(1.5, 414),
  },
  percentage: {
    fontSize: RFValue(4, 414),
    color: "#FFF",
    fontFamily: "montserrat-bold-english",
  },
  SnapAdCard: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderColor: globalColors.orange,
    borderWidth: 2,
    borderRadius: RFValue(10, 414),
    height: RFValue(35.5, 414),
    width: RFValue(33.5, 414),
    marginVertical: RFValue(6.25, 414),
    marginHorizontal: RFValue(5.5, 414),
    // flex: 1,
  },
  inputMiddleButton: {
    position: "absolute",
    backgroundColor: globalColors.transparent,
    alignSelf: "center",
    width: RFValue(45, 414),
    height: RFValue(45, 414),
    borderRadius: RFValue(22.5, 414),
    borderColor: "transparent",
    flexDirection: "column",
    opacity: 1,
  },
  holdToDeleteText: {
    color: globalColors.white,
    fontSize: RFValue(6, 414),
    textAlign: "center",
    fontFamily: "montserrat-regular",
  },

  carouselEditMedia: {
    flexDirection: "row",
    alignItems: "flex-end",
    height: "100%",
    position: "absolute",
    bottom: 0,
    paddingBottom: RFValue(5, 414),
    width: "100%",
  },
  carouselCardNumber: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RFValue(25, 414),
    backgroundColor: globalColors.orange,
    bottom: "20%",
  },
  carouselCardNumberText: {
    color: "#fff",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold-english",
  },
  SnapAdCard: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    borderColor: globalColors.orange,
    borderWidth: 2,
    borderRadius: RFValue(10, 414),
    height: RFValue(35.5, 414),
    width: RFValue(33.5, 414),
    marginVertical: RFValue(6.25, 414),
    marginHorizontal: RFValue(5.5, 414),
    // flex: 1,
  },
  inputMiddleButton: {
    position: "absolute",
    backgroundColor: globalColors.transparent,
    alignSelf: "center",
    width: RFValue(45, 414),
    height: RFValue(45, 414),
    borderRadius: RFValue(22.5, 414),
    borderColor: "transparent",
    flexDirection: "column",
    opacity: 1,
  },
  holdToDeleteText: {
    color: globalColors.white,
    fontSize: RFValue(6, 414),
    textAlign: "center",
    fontFamily: "montserrat-regular",
  },
  carouselFlatList: {
    paddingBottom: hp(24),
    alignItems: "center",
  },
  flatListView: { height: hp(5) < 40 ? hp(24) : hp(38) },

  carouselEditMedia: {
    flexDirection: "row",
    alignItems: "flex-end",
    height: "100%",
    position: "absolute",
    bottom: 0,
    paddingBottom: RFValue(5, 414),
    width: "100%",
  },
  carouselCardNumber: {
    width: RFValue(12, 414),
    height: RFValue(12, 414),
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RFValue(25, 414),
    backgroundColor: globalColors.orange,
    bottom: "20%",
  },
  carouselCardNumberText: {
    color: "#fff",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold-english",
  },
  swipeUpTitle: {
    fontFamily: "montserrat-bold",
    color: globalColors.purple,
    textTransform: "uppercase",
    fontSize: RFValue(6.5, 414),
  },
  clickContainer: {
    width: "90%",
    alignSelf: "center",
    top: RFValue(37.5, 414),
  },
});

export default styles;
