import { StyleSheet, PixelRatio, I18nManager } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../../GlobalStyles";
export const colors = {
  black: "#1a1917",
  gray: "#888888",
  background1: "#751AFF",
  background2: "#6268FF",
};
const styles = StyleSheet.create({
  safeAreaView: {
    // backgroundColor: "#0000",
    backgroundColor: globalColors.bluegem,
    height: "100%",
  },
  container: {
    backgroundColor: "#0000",
    display: "flex",
    justifyContent: "space-between",
    // zIndex: 5
  },
  backDrop: {
    position: "absolute",
    top: hp(5) < 30 ? -hp("73%") : -hp("63%"),
    alignSelf: "center",
  },
  block1: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    width: wp(100),
    paddingTop: RFValue(5, 414),
    zIndex: 1,
  },
  phoneicon: {
    alignSelf: "center",
    // marginTop: 20
  },
  mainContent: {
    // flex: 1,
    // justifyContent: 'flex-start',
    paddingBottom: hp(14),
    paddingTop: 0,
    paddingHorizontal: RFValue(13, 414),
  },
  scrollViewStyle: {
    marginTop: RFValue(7.5, 414),
    zIndex: 2,
  },
  input1: {
    marginBottom: RFValue(15, 414),
    // borderRadius: 15,
    alignSelf: "center",
    width: RFValue(150, 414),
    // height: 30,
    borderColor: "transparent",
    // backgroundColor: '#751AFF',
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: RFValue(15, 414),
  },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    borderRadius: RFValue(15, 414),
    marginBottom: I18nManager.isRTL ? -16 : -10,
  },
  inputText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7 / PixelRatio.getFontScale(), 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
    paddingVertical: RFValue(5, 414),
    borderBottomColor: "transparent",
    height: RFValue(25, 414),
  },
  minBudget: {
    color: "#fff",
    alignSelf: "center",
    fontSize: RFValue(5.5, 414),
    fontFamily: "montserrat-regular",
  },
  title: {
    fontSize: RFValue(8, 414),
    color: "#fff",
    textAlign: "center",
    fontFamily: "montserrat-bold",
    paddingTop: RFValue(15, 414),
  },
  input2: {
    paddingHorizontal: RFValue(25, 414),
    borderRadius: RFValue(15, 414),
    alignSelf: "center",
    top: RFValue(10, 414),
    borderColor: "transparent",
  },
  label: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    width: "100%",
  },
  downicon: {
    color: "#fff",
    fontSize: RFValue(10, 414),
  },
  popupOverlay: {
    height: "100%",
  },
  contentContainer: {
    marginTop: RFValue(7.5, 414),
    paddingTop: RFValue(7.5, 414),
    marginBottom: RFValue(7.5, 414),
  },
  dateInput: {
    marginBottom: 5,
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: 30,
    alignSelf: "center",
    width: RFValue(150, 414),
    height: RFValue(25, 414),
    justifyContent: "center",
    // borderWidth: 0.5,
  },
  dateLabel: {
    textAlign: "center",
    color: globalColors.orange,
    flexDirection: "column",
    fontFamily: "montserrat-regular",
    fontSize: RFValue(8, 414),
    // paddingHorizontal: 10
  },
  date: {
    fontFamily: "montserrat-bold",
    color: "#FF9D00",
    alignItems: "center",
    fontSize: RFValue(7, 414),
  },
  block1Title: {
    top: hp(5),
  },
  innerBlock1: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  dateContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  dateColumn: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  topContainer: {
    paddingVertical: RFValue(5, 414),
    width: RFValue(150, 414),
    flexDirection: "row",
    alignSelf: "center",
    // shadowOffset: { width: 1, height: 1 },
    // shadowColor: 'black',
    // shadowOpacity: 0.2,
  },
  collectionAdLinkForm2: {
    borderTopStartRadius: 0,
    borderBottomStartRadius: 0,
    borderBottomEndRadius: 40,
    borderTopEndRadius: 40,
  },
  collectionAdLinkForm1: {
    borderBottomEndRadius: 0,
    borderTopEndRadius: 0,
    borderBottomStartRadius: 40,
    borderTopStartRadius: 40,
  },
  button: {
    backgroundColor: "rgba(0,0,0,0.2)",
    width: RFValue(75, 414),
    height: RFValue(35, 414),
    justifyContent: "center",
    flexDirection: "column",
  },
  activeButton: {
    backgroundColor: "#FF9D00",
    width: RFValue(75, 414),
    height: RFValue(35, 414),
    justifyContent: "center",
    flexDirection: "column",
  },
  inactiveText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
  },
  activeText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    color: "#fff",
    textAlign: "center",
  },
  buttonSubText: {
    fontFamily: "montserrat-regular",
    paddingTop: 2,
    fontSize: RFValue(6, 414),
  },
  dateTextLabel: {
    borderTopLeftRadius: 150,
    borderTopRightRadius: 150,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    paddingTop: 8,
    width: 150,
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: 15,
    zIndex: 1,
  },
  objectiveTextLabel: {
    marginTop: RFValue(15, 414),
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  collectionAdView: {
    paddingTop: RFValue(5, 414),
  },
  collectionAdText: {
    color: "#FFFFFF",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold",
    textAlign: "center",
  },
  proceedButtonRTL: {
    width: RFValue(32.5, 414),
    height: RFValue(32.5, 414),
    // padding: 20
  },
  buttonView: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: RFValue(7.5, 414),
    // paddingHorizontal: RFValue(5, 414),
    // paddingVertical: 6,
  },
  btnHeadingText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    color: globalColors.black,
    textTransform: "uppercase",
    textAlign: "center",
    marginTop: RFValue(1.5, 414),
  },
  btnDescText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6, 414),
    color: globalColors.black,
    marginTop: RFValue(1.5, 414),
    textAlign: "center",
  },
  radioButtonView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: RFValue(17.5, 414),
    backgroundColor: "rgba(0,0,0,0.16)",
    flex: 1,
  },
  gradientBtn: {
    width: "50%",
    marginHorizontal: 0,
    height: RFValue(77.5, 414),
  },
  objectiveModal: {
    height: "76%",
    top: "5%",
    backgroundColor: "#fff",
    paddingTop: RFValue(10, 414),
    overflow: "hidden",
    borderRadius: RFValue(25, 414),
    width: "100%",
    alignSelf: "center",
  },
  minDurationText: {
    color: "#FFF",
    textAlign: "center",
    marginTop: RFValue(-10, 414),
    marginBottom: RFValue(7.5, 414),
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6, 414),
  },
});

export default styles;
