import { StyleSheet, PixelRatio, I18nManager } from "react-native";
import {
  heightPercentageToDP,
  widthPercentageToDP,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../../GlobalStyles";
export const colors = {
  black: "#1a1917",
  gray: "#888888",
  background1: "#751AFF",
  background2: "#751AFF",
};
const styles = StyleSheet.create({
  container: {
    backgroundColor: "transparent",
    marginTop: 0,
    flex: 1,
    // width: "100%"
    paddingHorizontal: RFValue(13, 414),
    // width: "96%"
  },
  contentContainer: {
    flex: 1,
  },
  appInstallContent: {
    flexDirection: "column",
    flex: 1,
    justifyContent: "space-around",
    paddingHorizontal: RFValue(20, 414),
  },
  titletext: {
    textAlign: "center",
    color: globalColors.purple,
    paddingTop: RFValue(5, 414),
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    paddingVertical: 0,
  },
  deepLinkContainer: {
    flex: 1,
    width: "100%",
    padding: RFValue(5, 414),
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  deepLinkHeader: {
    flexDirection: "column",
    width: "100%",
    alignItems: "center",
  },
  longFormVideoContainer: {
    flex: 1,
    alignItems: "center",
    padding: RFValue(5, 414),
  },
  longFormVideoContent: {
    flexDirection: "column",
    width: "100%",
    padding: RFValue(5, 414),
  },
  videoSelectButton: {
    backgroundColor: globalColors.purple,
    alignSelf: "center",
    marginVertical: RFValue(5, 414),
    borderRadius: RFValue(15, 414),
  },
  subtext: {
    bottom: RFValue(2.5, 414),
    alignSelf: "center",
    width: RFValue(150, 414),
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    paddingTop: RFValue(2.5, 414),
    color: globalColors.purple,
    paddingHorizontal: RFValue(10, 414),
    textAlign: "center",
  },
  subtextReach: {
    bottom: RFValue(2.5, 414),
    alignSelf: "center",
    width: RFValue(150, 414),
    fontFamily: "montserrat-bold",
    fontSize: RFValue(9, 414),
    lineHeight: RFValue(11, 414),
    paddingTop: RFValue(2.5, 414),
    color: "#fff",
    paddingHorizontal: RFValue(10, 414),
    textAlign: "center",
  },
  url: {
    alignSelf: "center",
    fontFamily: "montserrat-light-english",
    fontSize: RFValue(6.5, 414),
    color: "#fff",
    paddingRight: RFValue(10, 414),
    // textAlign: "left"
  },
  subTitle: {
    bottom: RFValue(2.5, 414),
    alignSelf: "center",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    paddingTop: RFValue(2.5, 414),
    color: "#fff",
    paddingHorizontal: RFValue(10, 414),
    textAlign: "center",
  },
  addVideoContainer: {
    backgroundColor: "#fff",
    borderRadius: RFValue(17.5, 414),
    padding: RFValue(5, 414),
    shadowColor: "#000",
    shadowOffset: {
      width: 1,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: RFValue(5, 414),
    elevation: RFValue(4, 414),
  },
  safeAreaContainer: {
    flex: 1,
  },
  warningText: {
    color: "#fff",
    textAlign: "center",
    top: RFValue(5, 414),
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6.5, 414),
  },
  listText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    color: "#fff",
    width: RFValue(85, 414),
  },
  footerText: {
    color: globalColors.purple,
    fontSize: RFValue(7, 414),
    fontFamily: "montserrat-regular",
    paddingBottom: 0,
    paddingTop: RFValue(15, 414),
    textDecorationLine: "underline",
    textAlign: "center",
    marginBottom: RFValue(5, 414),
  },
  textcontainer: {
    flexDirection: "column",
    alignItems: "center",
  },
  appTexts: {
    alignSelf: "center",
    fontFamily: "montserrat-medium",
    fontSize: widthPercentageToDP(3.2),
    marginBottom: RFValue(3, 414),
    color: "#fff",
    textAlign: "center",
  },
  video: {
    borderRadius: RFValue(25, 414),
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: globalColors.purple,
    width: RFValue(30, 414),
    height: RFValue(30, 414),
    justifyContent: "center",
  },
  placeholder: {
    borderRadius: RFValue(6.5, 414),
    overflow: "hidden",
    alignSelf: "center",
    width: "100%",
    height: RFValue(75, 414),
    zIndex: 0,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#fff",
    justifyContent: "center",
  },
  text: {
    color: "#fff",
    paddingBottom: RFValue(5, 414),
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    alignSelf: "center",
  },
  downArrowIcon: {
    color: "#fff",
    fontSize: RFValue(10, 414),
    left: 0,
  },
  deepLinkError: {
    color: "white",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    alignSelf: "center",
  },
  input: {
    backgroundColor: "rgba(0,0,0,0.2)",
    // paddingHorizontal : RFValue(5, 414),
    borderRadius: RFValue(75, 414),
    borderColor: "rgba(0,0,0,0)",
    alignSelf: "center",
    width: widthPercentageToDP(75),
    borderWidth: 0,
    height: RFValue(27, 414),
  },
  inputtext: {
    fontFamily: "montserrat-light-english",
    fontSize: 14 / PixelRatio.getFontScale(),
    alignSelf: "center",
    textAlign: "center",
    color: "#fff",
  },
  callActionLabel: {
    fontFamily: "montserrat-light-english",
    fontSize: RFValue(7, 414),
    textAlign: "center",
    color: "#fff",
    flex: 1,
  },
  websiteContent: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    padding: RFValue(10, 414),
  },
  whatsApp: {
    // minHeight: '100%',
    // backgroundColor: 'transparent',
    // flex: 1,
    flexDirection: "column",
    // justifyContent: 'space-around',
    // justifyContent: 'space-evenly',
    alignItems: "center",
    // bottom: "5%",
    paddingTop: RFValue(10, 414),
  },
  whatsAppDetailContainer: {
    paddingTop: RFValue(10, 414),
    // minHeight: '100%',
    // justifyContent: 'space-around',
    // flex: 1,
  },
  marginVertical: {
    marginVertical: RFValue(5, 414),
  },
  title: {
    textAlign: "center",
    color: "white",
    paddingBottom: RFValue(5, 414),
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
  },
  previewButtonContainer: {
    // paddingVertical : RFValue(20, 414),
  },
  videoPreviewView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  videoStyle: {
    width: "100%",
    minHeight: RFValue(100, 414),
    alignSelf: "center",
    //   flex: 1
    // marginTop: 30
    // height: 300
  },
  safeAreaViewLongFormVideoPreview: {
    paddingTop: RFValue(5, 414),
  },
  bottonViewWebsite: {
    marginBottom: RFValue(5, 414),
  },
  netLocStyle: {
    backgroundColor: "#5D1CD8",
    borderRadius: RFValue(5, 414),
    // marginRight : RFValue(25, 414),
    borderColor: "#5D1CD8",
    // width: "100%",
    width: widthPercentageToDP(20),
    height: RFValue(20, 414),
  },
  icon: {
    fontSize: RFValue(17.5, 414),
    color: "#fff",
    paddingLeft: RFValue(2.5, 414),
    alignSelf: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  inactivetext: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: "#fff",
    // paddingLeft: 10
  },
  activetext: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: "#FF9D00",
  },
  optionsContainer: {
    flexDirection: "column",
    paddingTop: RFValue(10, 414),
  },
  optionsRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    // paddingBottom: 20
  },
  optionsIconSize: {
    fontSize: RFValue(12.5, 414),
  },
  optionsTextContainer: {
    textAlign: "center",
    paddingLeft: RFValue(5, 414),
  },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: 12 / PixelRatio.getFontScale(),
    color: "#fff",
    alignSelf: "center",
    textAlign: "center",
    borderRadius: RFValue(15, 414),
    marginBottom: -10,
    marginTop: I18nManager.isRTL ? -5 : 0,
  },
  topContainer: {
    // paddingBottom : RFValue(15, 414),
    // paddingTop: widthPercentageToDP(5) > 10 ? 30 : 0,
    paddingVertical: RFValue(15, 414),
    // paddingHorizontal : RFValue(5, 414),
    width: widthPercentageToDP(75),
    // width : RFValue(150, 414),
    flexDirection: "row",
    alignSelf: "center",
    // shadowOffset: { width: 1, height: 1 },
    // shadowColor: 'black',
    // shadowOpacity: 0.2,
  },
  collectionAdLinkForm2: {
    borderTopStartRadius: 0,
    borderBottomStartRadius: 0,
    borderBottomEndRadius: RFValue(20, 414),
    borderTopEndRadius: RFValue(20, 414),
  },
  collectionAdLinkForm1: {
    borderBottomEndRadius: 0,
    borderTopEndRadius: 0,
    borderBottomStartRadius: RFValue(20, 414),
    borderTopStartRadius: RFValue(20, 414),
  },
  activeButton: {
    backgroundColor: "#FF9D00",
    height: RFValue(25, 414),
    // width : RFValue(75, 414),
    width: "50%",
    justifyContent: "center",
    flexDirection: "column",
  },
  inactiveText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    textTransform: "uppercase",
  },
  activeText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    color: "#fff",
    textAlign: "center",
    textTransform: "uppercase",
  },
  button2: {
    backgroundColor: "rgba(0,0,0,0.2)",
    // width : RFValue(75, 414),
    width: "50%",
    height: RFValue(25, 414),
    justifyContent: "center",
    flexDirection: "column",
  },
  inputContainer: {
    flexDirection: "row",
    // width: '100%',
    width: widthPercentageToDP(75),
    justifyContent: "center",
    alignSelf: "center",
  },
  websiteView: {
    alignItems: "center",
    width: "100%",
  },
  websiteLabelView: {
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomRightRadius: RFValue(10, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  networkLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    textAlign: "center",
    color: "#fff",
    // flex: 1,
    // paddingLeft : RFValue(10, 414),
    top: 2,
    // right : RFValue(2, 414),
  },
  callToActionLabelView: {
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomRightRadius: RFValue(10, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    paddingTop: RFValue(4, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: RFValue(7.5, 414),
    zIndex: 1,
  },
  businessInputText: {
    fontFamily: "montserrat-bold",
    fontSize: 14 / PixelRatio.getFontScale(),
    alignSelf: "center",
    textAlign: "center",
    color: "#FF9D00",
  },
  scrollViewContainer: {
    // paddingLeft : RFValue(10, 414),
    flexGrow: 1,
    paddingBottom: heightPercentageToDP(35),
    top: RFValue(5, 414),
  },
  businessNameView: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  BlurView: {
    zIndex: RFValue(5, 414),
    height: "100%",
  },
  walletPaymentModalContainer: {
    height: "100%",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  walletButton: {
    backgroundColor: "#FF9D00",
    marginTop: RFValue(7.5, 414),
    borderRadius: RFValue(5, 414),
    paddingHorizontal: RFValue(10, 414),
    alignSelf: "center",
    justifyContent: "center",
  },
  colorWhite: {
    color: "#fff",
  },
  instagramWarningHeadingText: {
    fontSize: RFValue(8, 414),
    lineHeight: RFValue(9, 414),
    textAlign: "center",
    color: "#FFF",
    fontFamily: "montserrat-bold",
    paddingVertical: RFValue(10, 414),
    // paddingHorizontal : RFValue(30, 414),
    width: widthPercentageToDP(50),
  },
  instagramWarningDescriptionText: {
    fontSize: RFValue(8, 414),
    lineHeight: RFValue(9.5, 414),
    textAlign: "center",
    color: "#FFF",
    fontFamily: "montserrat-regular",
    paddingVertical: RFValue(10, 414),
    paddingHorizontal: RFValue(10, 414),
    width: widthPercentageToDP(85),
  },
  instagramErrorText: {
    paddingTop: RFValue(6, 414),
    paddingHorizontal: RFValue(25, 414),
    fontSize: RFValue(7, 414),
    fontFamily: "montserrat-regular",
    color: "#fff",
    textAlign: "center",
  },
  proceedButtonRTL: {
    width: RFValue(27.5, 414),
    height: RFValue(27.5, 414),
    backgroundColor: globalColors.orange,
    borderRadius: RFValue(27.5, 414),
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: RFValue(2, 414),
    // padding: 20
  },
  customModalField: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 1,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: RFValue(5, 414),
    elevation: RFValue(4, 414),
    width: widthPercentageToDP(65),
  },
});

export default styles;
