import { StyleSheet, Platform, PixelRatio, I18nManager } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import { heightPercentageToDP } from "react-native-responsive-screen";
import { globalColors } from "../../../../GlobalStyles";
export const colors = {
  black: "#1a1917",
  gray: "#888888",
  background1: "#751AFF",
  background2: "#751AFF",
};
const styles = StyleSheet.create({
  safeArea: {
    height: "100%",
    flex: 1,
    backgroundColor: "#0000",
  },
  mainContainer: {
    // backgroundColor: 'rgba(255, 255, 255, 0.3)',
    backgroundColor: "#0000",
  },
  container: {
    // borderTopRightRadius: 30,
    // borderTopLeftRadius: 30,
    backgroundColor: "#0000",
    // marginTop: hp(2),
    overflow: "hidden",
    width: "100%",
    height: "100%",
    flex: 1,
  },
  backgroundViewWrapper: {
    ...StyleSheet.absoluteFillObject,
  },
  imageBackgroundViewWrapper: {
    position: "absolute",
    // left: -60,
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  videoBackgroundViewWrapper: {
    width: "100%",
    height: "100%",
  },
  contentContainer: {
    height: "93%",
    // paddingTop: ,
  },
  subHeadings: {
    color: globalColors.gray,
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    paddingVertical: RFValue(2.5, 414),
    paddingHorizontal: RFValue(15, 414),
    textAlign: "left",
  },
  setBudgetText: {
    paddingHorizontal: RFValue(5, 414),
    fontSize: RFValue(7, 414),
    flex: 1,
  },
  moneyInputContainer: {
    flexDirection: "column",
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 15,
    alignSelf: "center",
    justifyContent: "space-around",
    paddingVertical: 10,
  },
  budget: {
    alignSelf: "center",
    color: "#FF9D00",
    fontSize: 25 / PixelRatio.getFontScale(),
    fontFamily: "montserrat-medium",
    textAlign: "center",
    width: "100%",
    paddingBottom: 0,
    width: "100%",
  },
  moreOptionsText: {
    alignSelf: "center",
    color: "#FF9D00",
    fontSize: 14,
    fontFamily: "montserrat-medium",
    textAlign: "center",
    width: "100%",
    bottom: 20,
  },
  budgetInstructionText: {
    color: "#fff",
    fontSize: 11,
    alignSelf: "center",
    paddingHorizontal: 20,
  },
  sliderContainer: {
    marginHorizontal: 40,
    width: "100%",
    alignSelf: "center",
    paddingVertical: 10,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 40,
  },
  budgetSliderText: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    textAlign: "center",
    paddingBottom: 10,
  },
  slider: {
    width: "100%",
    height: 20,
  },
  sliderPlaceHolder: {
    height: RFValue(37.5, 414),
    justifyContent: "center",
  },
  targetList: {
    flexDirection: "column",
    // paddingBottom: 40,
    // height: "50%",
    marginHorizontal: 30,
  },
  targetTouchable: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    // marginVertical: 8,
    backgroundColor: "#fff",
    borderRadius: RFValue(25.5, 414),
    paddingHorizontal: 0,
    paddingVertical: RFValue(2.5, 414),
  },
  icon: {
    alignSelf: "center",
  },

  chart: {
    // bottom: 0,
    // width: widthPercentageToDP(25)
  },
  bottom: {
    flexDirection: "row",
    justifyContent: "center",
    paddingLeft: RFValue(5, 414),
    // height: "14%",
    alignItems: "center",
    alignSelf: "center",
    // width: "100%",
    bottom: heightPercentageToDP(5) < 30 ? RFValue(15, 414) : 0,
    position: "absolute",
    // flex: 0.55,
    backgroundColor: globalColors.white,
    borderTopWidth: 1,
    borderTopColor: "#75647C21",
    paddingVertical: RFValue(10, 414),
  },
  chartText: {
    textTransform: "uppercase",
    color: globalColors.rum,
    textAlign: "center",
    fontFamily: "montserrat-bold",
    fontSize: 13 / PixelRatio.getFontScale(),
  },
  chartTextNum: {
    color: globalColors.rum,
    fontFamily: "montserrat-regular-english",
    fontSize: 16,
    textAlign: "center",
    width: "100%",
    textTransform: "uppercase",
  },
  chartItems: {
    flexDirection: "row",
    // flex: 1,
  },
  reachBarLowerButton: {
    width: RFValue(50, 414),
    height: RFValue(25, 414),
  },
  reachPeopleView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    // width: "100%",
    flex: 1,
  },
  menutext: {
    paddingLeft:
      Platform.OS === "android" && I18nManager.isRTL ? 0 : RFValue(7.5, 414),
    paddingRight:
      Platform.OS === "android" && I18nManager.isRTL ? RFValue(7.5, 414) : 0,
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-semibold",
    color: globalColors.purple3,
    textAlign: "left",
    textTransform: "uppercase",
  },
  menudetails: {
    paddingLeft:
      Platform.OS === "android" && I18nManager.isRTL ? 0 : RFValue(7.5, 414),
    paddingRight:
      Platform.OS === "android" && I18nManager.isRTL ? RFValue(7.5, 414) : 0,
    color: globalColors.purple3,

    fontFamily: "montserrat-regular",
    fontSize: RFValue(6.5, 414),
    paddingVertical: RFValue(1, 414),
    textAlign: "left",
  },
  flex: {
    flex: 1,
  },
  menuComponentStyle: { top: 0 },
  reachView: {
    // flex: ,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "space-between",
    // width: "100%",
    marginHorizontal: 30,
  },
  existingButton: {
    borderWidth: 2,
    borderColor: "#9300FF",
    paddingHorizontal: 8,
    overflow: "visible",
    marginHorizontal: 0,
  },
  existingButtonText: { fontSize: 12, color: "#9300FF" },
  reachSubHeading: {
    color: globalColors.purple3,
    textTransform: "uppercase",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5 / PixelRatio.getFontScale(), 414),
  },
  reachTextNum: {
    color: globalColors.purple3,
    fontFamily: "montserrat-regular-english",
    fontSize: RFValue(5 / PixelRatio.getFontScale(), 414),
    textAlign: "left",
    width: "100%",
    textTransform: "uppercase",
  },
  expectedResultText: {
    color: globalColors.rum,
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold",
    textTransform: "uppercase",
    marginVertical: RFValue(2.5, 414),
    marginHorizontal: RFValue(10, 414),
    textAlign: "left",
  },
  reachInnerView: {
    flexDirection: "column",
    alignItems: "flex-start",
    marginLeft: 5,
  },
  bottomReachView: { flexDirection: "column", flex: 1 },
  subAudienceHeading: {
    paddingLeft: 10,
  },
  audienceHeading: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    color: globalColors.purple3,
    flex: 1,
    marginHorizontal: RFValue(2.5, 414),
    textTransform: "uppercase",
    textAlign: "left",
  },
  audienceCard: {
    backgroundColor: "#FFF",
    borderRadius: RFValue(15, 414),
    paddingHorizontal: RFValue(7.5, 414),
    paddingVertical: RFValue(5, 414),
    marginVertical: RFValue(2, 414),
  },
  lifetimeBudgetView: {
    backgroundColor: "#FFF",
    paddingHorizontal: 20,
    paddingVertical: 2,
    borderRadius: 30,
    alignItems: "center",
  },
  lifetimeBudgetText: {
    fontSize: RFValue(5, 414),
    paddingHorizontal: 0,
    color: globalColors.orange,
  },
  lifetimeBudgetNumber: {
    fontSize: RFValue(7, 414),
    paddingHorizontal: 0,
    paddingVertical: 0,
    fontFamily: "montserrat-bold-english",
  },
  selectAudienceText: {
    paddingHorizontal: RFValue(5, 414),
    width: "60%",
    fontSize: RFValue(7, 414),
    textAlign: "left",
    flex: 1,
  },
  createView: { flexDirection: "row", alignItems: "center" },
  createText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6, 414),
    // color: "#9325FF",
    color: globalColors.bluegem,
  },
  iconRight: {
    fontSize: RFValue(10, 414),
    color: globalColors.purple,
  },
  iconLoading: {
    right: "100%",
  },
  iconAdd: { marginHorizontal: 5 },
  genderOuterView: {
    display: "flex",
    flexDirection: "row",
    padding: RFValue(2.5, 414),
  },
  genderInnerView: {
    borderWidth: 1,
    borderRadius: RFValue(10, 414),
    paddingHorizontal: RFValue(5, 414),
    // paddingVertical: 5,
    marginHorizontal: RFValue(2.5, 414),
    borderColor: globalColors.purple3,
  },
  genderRadioText: {
    color: globalColors.purple3,
    fontSize: RFValue(6.5, 414),
    fontFamily: "montserrat-regular",
    lineHeight: 29,
  },
  genderInnerActiveView: {
    borderColor: globalColors.purple,
    backgroundColor: globalColors.purpleTran,
  },
  genderRadioTextActive: {
    color: globalColors.purple,
  },
  selectLanguageButton: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    paddingHorizontal: RFValue(5, 414),
    paddingVertical: RFValue(1.5, 414),
    borderColor: globalColors.purple3,
    borderRadius: RFValue(10, 414),
    marginHorizontal: RFValue(5, 414),
    marginVertical: RFValue(1.5, 414),
  },
  selectLanguageText: {
    fontFamily: "montserrat-regular",
    color: globalColors.purple3,
    fontSize: RFValue(6.5, 414),
  },
  ageText: {
    color: globalColors.purple,
    fontSize: RFValue(6.5, 414),
    fontFamily: "montserrat-regular",
    textAlign: "center",
  },

  toText: {
    marginHorizontal: RFValue(7.5, 414),
    color: globalColors.purple3,
    fontSize: RFValue(6.5, 414),
    fontFamily: "montserrat-regular",
  },

  ageView: {
    borderWidth: 1,
    borderColor: globalColors.purple3,
    borderRadius: RFValue(10, 414),
    paddingHorizontal: RFValue(10, 414),
    paddingVertical: RFValue(3, 414),
    justifyContent: "center",
  },
  ageOuterView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: RFValue(2.5, 414),
    paddingLeft: RFValue(5, 414),
  },
  iconDown: {
    color: globalColors.purple,
    right: 2,
    fontSize: RFValue(11, 414),
  },
  interestText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7, 414),
    color: globalColors.purple3,
    flex: 1,
    textTransform: "uppercase",
    textAlign: "left",
    paddingHorizontal: RFValue(5, 414),
  },
  interestView: {
    alignSelf: "center",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  swipesView: { flexDirection: "row", alignItems: "center" },
  impressionsView: { flexDirection: "row", alignItems: "center" },
  interestTargetTouchable: {
    marginVertical: RFValue(4, 414),
    paddingHorizontal: RFValue(5, 414),
  },
});

export default styles;
