import { StyleSheet, PixelRatio, Platform, I18nManager } from "react-native";
import {
  widthPercentageToDP,
  heightPercentageToDP,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../GlobalStyles";

const styles = StyleSheet.create({
  safeAreaViewContainer: {
    flex: 1,
    backgroundColor: "#FFF",
    // position: "absolute"
  },
  personalInfoIcon: {
    alignSelf: "center",
    marginTop: RFValue(10, 414),
  },
  dataContainer: {
    paddingHorizontal: 35,
    paddingTop: RFValue(10, 414),
    alignItems: "center",
  },
  nameText: {
    color: "#5F5F5F",
    fontFamily: "montserrat-medium",
    fontSize: 23,
    textAlign: "left",
    paddingBottom: 60,
  },
  itemMobileNo: {
    marginBottom: 30,
  },
  labelMobileNo: {
    fontSize: 14 / PixelRatio.getFontScale(),
  },
  labelEmail: {
    bottom: 5,
    // alignSelf: "center",
    fontSize: Platform.OS === "android" ? 14 / PixelRatio.getFontScale() : 14,
  },
  mainCard: {
    flex: 1,
  },
  button: {
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 3,
    shadowOpacity: 0.2,
  },
  contentContainer: {
    paddingVertical: RFValue(10, 414),
    justifyContent: "space-around",
  },
  label: {
    color: "#FF9D00",
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    textAlign: "left",
  },
  inputText: {
    fontFamily: "montserrat-regular-english",
    textAlign: I18nManager.isRTL ? "right" : "left",
    fontSize: 21 / PixelRatio.getFontScale(),
    color: "#4B4B4B",
  },
  input: {
    // bottom: 25,
    marginBottom: 10,
    // alignSelf: "center",
    // width: "90%",
    // height: 45,
    borderColor: "#7039FF",
  },
  input: {
    backgroundColor: "rgba(0,0,0,0.2)",
    // paddingHorizontal: 10,
    borderRadius: RFValue(75, 414),
    borderColor: "rgba(0,0,0,0)",
    alignSelf: "center",
    width: "100%",
    borderWidth: 0,
    height: RFValue(27, 414),
  },
  inputtext: {
    fontFamily: "montserrat-light",
    fontSize: RFValue(7 / PixelRatio.getFontScale(), 414),
    alignSelf: "flex-start",
    textAlign: I18nManager.isRTL ? "right" : "left",
    color: "#FFF",
    marginBottom: RFValue(5, 414),
    paddingLeft: 0,
    paddingRight: 0,
    height: RFValue(10, 414),
  },
  fullNameView: {
    width: "100%",
  },
  phoneInput: {
    borderRadius: 0,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    paddingBottom: RFValue(5, 414),
    marginTop: RFValue(5, 414),
  },
  mobileView: {
    width: "100%",
    marginBottom: RFValue(15, 414),
  },
  emailItem: { width: "100%", marginTop: 25 },
  inputLabel: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    color: "#FFF",
    textAlign: "left",
    textTransform: "uppercase",
    marginTop: RFValue(5, 414),
    zIndex: 1,
  },
  labelView: {
    height: RFValue(7.5, 414),
    width: RFValue(75, 414),
    alignSelf: "center",
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    borderBottomRightRadius: RFValue(10, 414),
    paddingTop: 2,
    marginBottom: 0,
    backgroundColor: "rgba(0,0,0,0.15)",
  },
  flagIcon: {
    fontSize: RFValue(6, 414),
    paddingLeft: 0,
    paddingRight: 0,
  },
  flagStyle: {
    height: 15,
  },
  stepNoView: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: RFValue(10, 414),
    borderColor: "#C6C6C6",
  },
  stepNoText: {
    fontFamily: "montserrat-regular",
    fontSize: 10,
    color: "#C6C6C6",
  },
  stepNameText: {
    fontFamily: "montserrat-regular",
    fontSize: 8,
    color: "#C6C6C6",
  },
  horzintalLine: {
    borderWidth: 0.5,
    borderColor: "#C6C6C6",
    width: 30,
    alignSelf: "center",
    marginTop: -10,
  },
  gradient: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: RFValue(17.5, 414),
    borderTopRightRadius: RFValue(17.5, 414),
    // overflow: "hidden"
  },
  whatsAppDetailContainer: {
    paddingTop: RFValue(10, 414),
    paddingBottom: "50%",
    paddingHorizontal: RFValue(15, 414),
    // minHeight: '100%',
    // justifyContent: 'space-around',
    // flex: 1,
  },
  marginVertical: {
    marginVertical: 10,
  },
  callToActionLabelView: {
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomRightRadius: RFValue(10, 414),
    borderBottomLeftRadius: RFValue(10, 414),
    paddingTop: 4,
    marginBottom: 0,
    width: RFValue(75, 414),
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.2)",
    height: 15,
    zIndex: 1,
  },
  createWebsiteText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    color: "#FFF",
    width: widthPercentageToDP(75),
    textAlign: "center",
  },
  bottonViewWebsite: {
    marginBottom: 10,
    alignSelf: "flex-end",
    left: -10,
  },
  itemView: {
    width: 25,
    borderRadius: RFValue(10, 414),
    height: 25,
    marginBottom: -15,
    zIndex: 1,
    display: "flex",
    alignItems: "center",
    alignSelf: "flex-end",
    justifyContent: "center",
  },
  itemFoundText: {
    textAlign: "center",
    color: "#FFF",
  },
  itemProductView: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    // marginHorizontal: "auto",
    paddingHorizontal: 8,
    alignSelf: "flex-start",
  },
  imageProduct: {
    width: 95,
    height: 95,
    borderRadius: RFValue(10, 414),
  },
  viewMoreText: {
    fontFamily: "montserrat-bold",
    color: globalColors.orange,
    fontSize: RFValue(7, 414),
    lineHeight: 18,
    paddingVertical: 10,
    textAlign: "center",
    borderWidth: 1,
    borderColor: globalColors.orange,
    borderRadius: RFValue(10, 414),
    marginHorizontal: 60,
    marginVertical: 30,
  },
  submitText: {
    fontFamily: "montserrat-bold",
    color: "#FFF",
    fontSize: RFValue(7, 414),
    lineHeight: 18,
  },
  registerSuccessIcon: {
    marginLeft: I18nManager.isRTL
      ? widthPercentageToDP(-5)
      : widthPercentageToDP(-55),
    marginTop: heightPercentageToDP(5),
  },
  successText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
    color: "#FFF",
    textAlign: "left",
  },
  registerCompleteText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(13.5, 414),
    color: "#FFF",
    textAlign: "left",
    paddingTop: 10,
    textTransform: "uppercase",
  },
  yourLinkText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(9, 414),
    color: "#FFF",
    textAlign: "center",
    paddingVertical: 10,
    textTransform: "uppercase",
  },
  getStartedBtn: {
    height: RFValue(27, 414),
    marginHorizontal: 0,
  },

  mainView: {
    display: "flex",
    paddingHorizontal: RFValue(15, 414),
    paddingTop: 10,
    flexDirection: "column",
  },
  businessNameView: {
    flexDirection: "column",
    padding: RFValue(10, 414),
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: 70,
    marginBottom: RFValue(10, 414),
  },
  websiteUrl: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    lineHeight: 19,
    color: globalColors.orange,
    textAlign: "center",
  },
  tapCopyText: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6.5, 414),
    color: globalColors.white,
    textAlign: "center",
  },
  activeStepView: {
    borderColor: "#4CA2E0",
  },
  activeStepText: {
    color: "#4CA2E0",
    fontFamily: "montserrat-bold",
  },
  headerText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(9, 414),
    color: "#4CA2E0",
    textTransform: "uppercase",
  },
  badgeView: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  scrollView: {
    borderTopLeftRadius: RFValue(17.5, 414),
    borderTopRightRadius: RFValue(17.5, 414),
    marginTop: -110,
    backgroundColor: "#9300FF",
  },
  outerView: {
    flex: 1,
    borderTopLeftRadius: RFValue(17.5, 414),
    borderTopRightRadius: RFValue(17.5, 414),
    overflow: "hidden",
    zIndex: 10,
    elevation: 1,
    paddingHorizontal: RFValue(10, 414),
    // backgroundColor: "#9300FF",
    paddingTop: RFValue(10, 414),
  },
  onlineStoreHomeIcon: {
    left: -10,
    zIndex: -5,
    elevation: 0,
    backgroundColor: "#FFF",
    marginBottom: heightPercentageToDP(-15),
  },
  list: {
    // paddingTop: 20
    // display: "flex",
    // flexGrow: 1,
    // justifyContent: "space-around",
    alignItems: "center",
    paddingBottom: RFValue(10, 414),
    // flex: 1,
    // marginBottom: 40,
  },
  submitProducts: {
    width: "70%",
    height: 40,
    marginHorizontal: 60,
    alignSelf: "center",
    marginBottom: 30,
  },
  headerCardView: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#FFF",
  },
  badgeViewInner: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  changeLogoText: {
    textAlign: "center",
    fontSize: RFValue(5.5, 414),
    fontFamily: "montserrat-regular",
    color: globalColors.orange,
    paddingHorizontal: 5,
  },
  instagramErrorText: {
    // paddingTop: 12,
    // paddingHorizontal: 50,
    fontSize: RFValue(7, 414),
    fontFamily: "montserrat-regular",
    color: "#fff",
    textAlign: "center",
  },
  errorIcon: {
    position: "absolute",
    right: 15,
    alignSelf: "center",
    top: I18nManager.isRTL ? 35 : 30,
  },
  socialMediaIcon: {
    marginHorizontal: RFValue(10, 414),
  },
  selectProductText: {
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-regular",
    color: "#999999",
    paddingHorizontal: 50,
    textAlign: "left",
  },
  hideProductText: {
    fontFamily: "montserrat-bold",
    color: globalColors.orange,
  },
  productsText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    color: "#909090",
    textTransform: "uppercase",
  },
  step2OuterView: {
    overflow: "visible",
    paddingHorizontal: 0,
    paddingTop: 0,
    flex: 0,
    zIndex: 2,
  },
  livePreviewView: {
    backgroundColor: "#42EB56",
    paddingHorizontal: RFValue(8, 414),
    paddingVertical: 7,
    borderRadius: RFValue(10, 414),
    width: 120,
    zIndex: 22,
    left: 30,
    marginBottom: -15,
  },
  livePreviewText: {
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-bold",
    color: "#FFF",
  },
  previewOuterView: {
    display: "flex",
    alignItems: "center",
    overflow: "hidden",
    borderTopLeftRadius: RFValue(17.5, 414),
    borderTopRightRadius: RFValue(17.5, 414),
    paddingTop: 25,
    paddingBottom: 15,
  },
  profileIcon: {
    width: 62,
    height: 62,
    borderRadius: 70,
  },
  bsnNameText: {
    textAlign: "center",
    fontSize: RFValue(8.5, 414),
    fontFamily: "montserrat-bold",
    textTransform: "uppercase",
    color: "#FFF",
    paddingBottom: 5,
  },
  socialMediaView: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
  },
  productSelectOuterView: {
    // flex: 1,
    backgroundColor: "#5600CB",
  },
  productsTextView: {
    alignSelf: "center",
    backgroundColor: "#FFF",
    paddingTop: 10,
    paddingHorizontal: 50,
    borderTopLeftRadius: RFValue(75, 414),
    borderTopRightRadius: RFValue(75, 414),
    borderBottomRightRadius: 25,
    marginBottom: -4,
    zIndex: 1,
  },
  selectProductTextView: {
    // flex: 1,
    backgroundColor: "#FFF",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: RFValue(10, 414),
  },
  lowerBtn: {
    marginBottom: 30,
  },
  eachItem: {
    width: 65,
    height: 65,
    borderRadius: RFValue(10, 414),
  },
  itemFound: {
    opacity: 0.26,
  },
  itemFoundView: {
    backgroundColor: "#D84D28",
  },
  businesslogoView: {
    width: 95,
    height: 95,
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.16)",
    marginVertical: 10,
    borderRadius: 100,
    overflow: "hidden",
  },
  businessLogo: {
    width: 140,
    height: 140,
  },
  yourUrlText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(6, 414),
    color: "#FFF",
    textTransform: "uppercase",
    textAlign: "left",
    marginTop: 10,
    zIndex: 1,
  },
  weburl: {
    fontFamily: "montserrat-regular-english",
    fontSize: RFValue(7, 414),
    color: "#FFF",
    textAlign: "left",
  },
  weburlView: {
    marginHorizontal: 26,
    // flexDirection: "row"
  },
  copyIcon: {
    alignSelf: "flex-end",
    left: 10,
  },
  copyIcon2: {
    position: "absolute",
    right: RFValue(10, 414),
    top: I18nManager.isRTL ? 35 : 30,
  },
  urlView: {
    marginBottom: 13,
  },
  award: {
    alignSelf: "center",
  },
  colView: {
    display: "flex",
    flexDirection: "column",
    alignSelf: "center",
    marginLeft: 13,
    width: "100%",
  },
  businessLogoImage: {
    width: 95,
    height: 95,
  },
  changeLogoView: {
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    marginBottom: 13,
  },
  scrollViewContainer: {
    backgroundColor: "#f8f8f8",
  },
});

export default styles;
