import { StyleSheet, PixelRatio, I18nManager } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";
import { globalColors } from "../../../GlobalStyles";

const styles = StyleSheet.create({
  container: {
    // height: "100%",
    backgroundColor: "#f8f8f8",
  },
  media: {
    alignSelf: "center",
    height: hp("5"),
    width: hp("5"),
  },
  reviewtext: {
    fontFamily: "montserrat-medium",
    fontSize: RFValue(6.5, 414),
    padding: RFValue(1.5, 414),
    color: "#fff",
    textAlign: "center",
  },
  adStatus: {
    borderRadius: RFValue(8, 414),
    marginBottom: RFValue(2.5, 414),
    paddingHorizontal: RFValue(5, 414),
    top: RFValue(20, 414),
    left: "22%",
    alignItems: "center",
    position: "absolute",
    flexDirection: "row",
  },
  mainCard: {
    height: "100%",
    overflow: "hidden",
    borderBottomStartRadius: RFValue(15, 414),
    borderBottomEndRadius: RFValue(15, 414),
  },
  text: {
    textAlign: "center",
    color: "#fff",
    paddingTop: RFValue(20, 414),
    paddingBottom: RFValue(5, 414),
    fontFamily: "montserrat-regular",
    fontSize: RFValue(6.5, 414),
    paddingHorizontal: RFValue(5, 414),
    paddingVertical: RFValue(5, 414),
  },
  buttontext: {
    fontFamily: "montserrat-regular",
    fontSize: RFValue(7, 414),
  },
  inputtext: {
    fontFamily: "montserrat-light",
    fontSize: RFValue(7 / PixelRatio.getFontScale(), 414),
    alignSelf: "center",
    textAlign: "center",
  },

  button: {
    alignSelf: "center",
    backgroundColor: "transparent",
    position: "absolute",
    bottom: hp("5%"),
    elevation: 0,
  },

  categories: {
    textAlign: "left",
    color: "#fff",
    flexDirection: "column",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(8, 414),
    paddingHorizontal: RFValue(5, 414),
  },
  categoryView: {
    flexDirection: "row",
    padding: RFValue(2.5, 414),
    // alignSelf: "flex-start"
  },
  subHeadings: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(7.5, 414),
    paddingVertical: hp("1"),
  },

  title: {
    color: globalColors.purple,
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    textAlign: "left",
    textTransform: "uppercase",
  },
  titleMedia: {
    fontSize: RFValue(8, 414),
    color: "#fff",
    paddingVertical: RFValue(5, 414),
    fontFamily: "montserrat-bold",
    textTransform: "uppercase",
    textAlign: "left",
  },
  urlText: {
    fontSize: RFValue(6, 414),
    color: "#fff",
    paddingVertical: RFValue(5, 414),
    fontFamily: "montserrat-regular",
    textAlign: "left",
  },
  chartTitle: {
    color: "#fff",
    fontFamily: "montserrat-bold",
    fontSize: RFValue(10, 414),
    width: RFValue(75, 414),
  },
  subtext: {
    fontFamily: "montserrat-light",
    fontSize: RFValue(7.5, 414),
    color: "#fff",
  },
  numbers: {
    textAlign: "center",
    color: globalColors.orange,
    fontFamily: "montserrat-bold-english",
    fontSize: RFValue(8, 414),
  },
  toggleSpace: {
    top: hp("2"),
    height: hp("10"),
  },
  icon: {
    flexDirection: "column",
    alignSelf: "center",
    color: "#FF790A",
    fontSize: RFValue(16.5, 414),
  },
  gender: {
    // ...StyleSheet.absoluteFillObject,
    left: 17,

    top: RFValue(2.5, 414),

    transform: [{ rotate: "-45deg" }],
  },
  optionalTargets: {
    flexDirection: "column",
    marginBottom: RFValue(5, 414),
    // alignSelf: "center"
  },
  gradient: {
    ...StyleSheet.absoluteFillObject,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
  },
  backgroundViewWrapper: {
    justifyContent: "center",
    overflow: "hidden",
    width: "100%",
    height: "100%",
    borderRadius: RFValue(20, 414),
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  toggleStyle: {
    marginTop: 0,
    width: wp("28"),
    height: hp("4"),
    borderRadius: RFValue(12.5, 414),
    padding: 0,
  },
  circleStyle: {
    width: RFValue(12.5, 414),
    height: RFValue(12.5, 414),
    borderRadius: RFValue(9.5, 414),
  },

  btnClose: {
    position: "absolute",
    top: hp("5%"),
    left: wp("10%"),
    height: 100,
    width: 100,
  },
  BlurView: {
    height: "100%",
    paddingTop: hp("15%"),
  },
  pauseDes: {
    fontFamily: "montserrat-light",
    fontSize: RFValue(7, 414),

    marginVertical: RFValue(10, 414),
    padding: RFValue(10, 414),
  },
  dragHandler: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  bottomContainer: {
    width: wp("100"),
    flex: 1,
    // elevation: RFValue(5, 414),
    zIndex: RFValue(5, 414),
    alignItems: "center",
    justifyContent: "center",
  },
  tab: {
    // position: "absolute",
    backgroundColor: "#000",
    top: RFValue(7.5, 414),
    alignSelf: "center",
    width: wp("63%"),
    borderRadius: RFValue(15, 414),
    paddingBottom: RFValue(10, 414),
  },
  handlerIcon: {
    position: "absolute",
    left: wp("26%"),
    top: -10,
    zIndex: 2,
  },
  handlerText: {
    textAlign: "center",
    color: "#fff",
    paddingTop: I18nManager.isRTL ? 0 : RFValue(12.5, 414),
    paddingBottom: I18nManager.isRTL ? 0 : RFValue(10, 414),
    fontFamily: "montserrat-medium",
    fontSize: 18,
    bottom: I18nManager.isRTL ? -5 : RFValue(2.5, 414),
    // zIndex: 1
  },
  boxStats: {
    top: RFValue(15, 414),
    width: 140,
    paddingVertical: "4%",
    paddingHorizontal: "5%",
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: RFValue(7.5, 414),
  },
  wideBoxStat: {
    width: "83%",
    alignSelf: "center",
    paddingVertical: "3%",
    top: "18%",
  },
  stats: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "montserrat-medium",
    fontSize: RFValue(7, 414),
    alignSelf: "center",
  },
  editButton: {
    position: "absolute",
    left: wp(85),
    top: hp(10),
    fontFamily: "montserrat-regular",
  },
  switchButtonTex: {
    fontFamily: "montserrat-medium",
    fontSize: RFValue(5, 414),
    color: "#fff",
    top: 7,
    textAlign: "center",
  },
  switchCircle: {
    width: wp("13"),
    height: hp("3.8"),
    borderRadius: RFValue(12.5, 414),
    flexDirection: "column",
    justifyContent: "center",
  },
  statusText: {
    fontFamily: "montserrat-medium",
    fontSize: RFValue(5, 414),
    paddingTop: RFValue(2.5, 414),
    color: "#fff",
    textAlign: "center",
  },
  choicesStyles: {
    // elevation: RFValue(5.5, 414),
    zIndex: RFValue(5.5, 414),
    position: "absolute",
    // width: "100%",
    left: RFValue(10, 414),
    right: RFValue(10, 414),
    // width: "100%",
    // marginHorizontal: RFValue(10, 414),
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-between",
    borderRadius: RFValue(15, 414),
  },
  choiceButtons: {
    elevation: 0,
    borderRadius: RFValue(15, 414),
    width: 100,
    justifyContent: "center",
    paddingVertical: RFValue(5, 414),
  },
  choiceText: {
    fontFamily: "montserrat-bold",
    color: "#fff",
    textAlign: "center",
  },
  boxStatsRow: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    top: hp(4),
  },
  mainMetrics: {
    // top: RFValue(25, 414),
    flex: 1,
  },
  statusButtonsText: {
    fontFamily: "montserrat-medium",
    color: "#fff",
    backgroundColor: "transparent",
  },
  statusButtons: {
    borderRadius: RFValue(5, 414),
    borderColor: globalColors.orange,
    borderWidth: 0.5,
    alignSelf: "center",
    marginVertical: RFValue(2.5, 414),
    padding: RFValue(5, 414),
    width: "40%",
    justifyContent: "center",
  },
  switchButtonText: {
    fontSize: RFValue(5, 414),
    color: "#fff",
    alignSelf: "center",
    justifyContent: "center",
  },
  placeHolderChart: {
    position: "absolute",
    zIndex: RFValue(5, 414),
    display: "flex",
    flex: 1,
    width: wp(90),
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    // borderRadius: RFValue(7.5, 414),
  },
  ScrollChartArea: {
    height: RFValue(17.5, 414),
  },
  placeHolderChartText: {
    fontFamily: "montserrat-medium",
    color: "#000",
  },
  dot: {
    top: RFValue(5, 414),
    width: RFValue(5, 414),
    height: RFValue(5, 414),
    marginHorizontal: RFValue(5, 414),
    borderRadius: RFValue(25, 414),
    backgroundColor: globalColors.orange,
  },
  reviewButton: {
    alignSelf: "center",
    borderRadius: RFValue(6, 414),
    top: "10%",
    padding: RFValue(10, 414),
    backgroundColor: globalColors.orange,
  },
  campaignMediaAndInfo: {
    flexDirection: "row",
    width: "100%",
    height: RFValue(125, 414),
    marginBottom: hp(8),
    marginVertical: RFValue(5, 414),
    justifyContent: "space-evenly",
  },
  titleHeader: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  targetingContainer: {
    flexDirection: "column",
    backgroundColor: "#0005",
    width: "100%",
    borderRadius: RFValue(20, 414),
    justifyContent: "center",
    padding: RFValue(5, 414),
  },
  storyOrCollectionStyle: {
    borderRadius: RFValue(20, 414),
    width: "100%",
    height: "75%",
    position: "absolute",
    top: "16%",
    left: "7%",
    opacity: 0.4,
  },
  metricsStylePurple: {
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
    // flex: 1,
    paddingHorizontal: RFValue(10, 414),
    marginVertical: RFValue(1.5, 414),
    marginHorizontal: RFValue(5, 414),
    backgroundColor: "#0003",
    width: RFValue(80, 414),
    borderRadius: RFValue(10, 414),
    height: RFValue(25, 414),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: RFValue(1.5, 414),
    },
    // elevation: 7,
    // padding: "3%"
  },
  metricsStyle: {
    flexDirection: "row",
    alignItems: "center",
    // flex: 1,
    paddingHorizontal: RFValue(10, 414),
    marginVertical: RFValue(1.5, 414),
    marginHorizontal: RFValue(5, 414),
    backgroundColor: "#FFF",
    width: RFValue(80, 414),
    borderRadius: RFValue(10, 414),
    height: RFValue(25, 414),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: RFValue(1.5, 414),
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 7,
    // padding: "3%"
  },
  chartChoices: {
    justifyContent: "center",
  },
  chartChoiceButtons: {
    // width: I18nManager.isRTL ? null : "20%",
    height: RFValue(17.5, 414),
  },
  chartChoiceText: {
    fontSize: 10 / PixelRatio.getFontScale(),
    width: "125%",
  },
  pauseModalTitle: {
    fontFamily: "montserrat-bold",
    color: "#fff",
    textTransform: "uppercase",
    fontSize: RFValue(10, 414),
    textAlign: "center",
  },
  mediaPreviewLowerButton: {
    width: RFValue(17.5, 414),
    height: RFValue(17.5, 414),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF9D00",
    borderRadius: RFValue(12.5, 414),
  },
  placeholderView: {
    margin: RFValue(2.5, 414),
  },
  xAxisStyle: {
    position: "absolute",
    backgroundColor: "#0000",
    width: "15%",
  },
  CSVText: {
    fontFamily: "montserrat-regular",
    color: "#fff",
    textAlign: "center",
    width: "80%",
    alignSelf: "center",
    fontSize: RFValue(7, 414),
  },
  circleIcon: { color: "#fff", fontSize: RFValue(7, 414) },
  reviewText: {
    fontFamily: "montserrat-bold",
    fontSize: RFValue(5.5, 414),
    paddingHorizontal: RFValue(2.5, 414),
    color: "#fff",
    textTransform: "uppercase",
  },
  campaignStatus: {
    borderRadius: RFValue(8, 414),
    marginBottom: RFValue(2.5, 414),
    paddingHorizontal: RFValue(5, 414),
    width: "30%",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#66D072",
  },
  chartChoicesView: {
    height: "10%",
    width: "85%",
    alignSelf: "center",
    marginTop: RFValue(5, 414),
  },
  chartChoicesViewContainer: {
    elevation: RFValue(5.5, 414),
    zIndex: RFValue(5.5, 414),
    // width: "100%",
    flexDirection: "row",
    // marginRight: wp(10),
    alignSelf: "center",
    marginTop: RFValue(7.5, 414),
    paddingBottom: RFValue(5, 414),
    // justifyContent: "space-around",
    justifyContent: "center",
    alignItems: "center",
  },
  remainingBudgetContainer: {
    backgroundColor: globalColors.orange,
    width: "90%",
    height: RFValue(25, 414),
    borderRadius: RFValue(25, 414),
    alignSelf: "center",
    top: RFValue(2.5, 414),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    marginVertical: RFValue(5, 414),
  },
  remainingBudgetText: {
    fontFamily: "montserrat-regular",
    color: "white",
    fontSize: RFValue(6.5, 414),
    width: "85%",
    textAlign: "left",
  },
  destinationView: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0,0.16)",
    paddingHorizontal: RFValue(15, 414),
    paddingVertical: RFValue(7.5, 414),
    borderRadius: RFValue(15, 414),
    marginHorizontal: RFValue(5, 414),
  },
  destinationText: {
    color: "#FFFFFF",
    fontSize: RFValue(6, 414),
    fontFamily: "montserrat-regular",
  },
  attachementText: {
    color: "#FFFFFF",
    fontSize: RFValue(7, 414),
    fontFamily: "montserrat-bold",
    textTransform: "uppercase",
    paddingHorizontal: 20,
    paddingBottom: 4,
  },
  copyIcon: {
    alignSelf: "flex-end",
    left: RFValue(4, 414),
  },
});
export default styles;
